// VF systems pages — content pack C: P·11–P·14 + P·16.
// Grounded on research pack C (2026-09-11). Honesty law applies: no invented stats, guardrails obeyed.

export default [

// ─── P·11 LOW-RESOURCE LANGUAGE AI ───────────────────────────────────
{
  slug: 'low-resource-language-ai',
  name: 'Low-Resource Language AI',
  pn: 'P·11',
  sector: 'LANGUAGE',
  titleTag: 'AI for the Languages Big Tech Skips',
  metaDesc: 'Low-Resource Language AI by VF Empire — translation, teaching and preservation for underserved languages. Maltese included; this one is personal. In build in Malta, EU.',
  ogTitle: 'Seven thousand languages. AI speaks a few hundred.',
  ogDesc: 'Translation, learning and preservation infrastructure for the languages underserved by big-tech platforms — starting with Maltese. On the VF build slate.',
  appCategory: 'UtilitiesApplication',
  os: 'Web, iOS, Android',
  ldDesc: 'Low-Resource Language AI is a language-technology programme in development by VF Empire Corp Ltd: translation, language learning and preservation tooling for languages underserved by mainstream AI platforms, beginning with Maltese.',
  img: 'p11',
  tagline: 'A language dies quietly.<br><em class="i">Or it gets infrastructure.</em>',
  sub: 'Google Translate covers roughly 249 of the world’s ~7,000 languages. The rest — including most of Europe’s smaller tongues — live outside the AI era looking in. This programme builds the missing infrastructure, starting with the language of our own home: Maltese.',
  chips: ['MALTESE FIRST', 'PRESERVATION-GRADE', 'COMMUNITY CORPUS'],
  heroAlt: 'Minimal 3D render of speech bubbles with one small blue bubble among them — Low-Resource Language AI by VF Empire',
  whyH: 'The digital age has a language policy.<br><span class="mute">Nobody voted for it.</span>',
  whyLead: 'Which languages get AI is decided by market size, not by the people who speak them. The result is a quiet sorting of the world’s languages into those with a digital future and those without.',
  fails: [
    { h: 'Coverage is a rounding error', p: 'Around 249 languages on Google Translate, out of roughly 7,000 spoken. Researcher András Kornai estimated fewer than 5% of languages are ascending into digital use at all — the rest are digitally static or sinking.' },
    { h: 'Europe is not exempt', p: 'The META-NET studies rated 21 of 30 European languages as having weak or no support in key language-technology areas. Maltese — an official EU language — scored in the lowest band in every category studied.' },
    { h: 'Endangerment is accelerating', p: 'UNESCO estimates around 40% of the world’s languages are endangered. Digital absence compounds it: a language your phone cannot speak is a language your children practise less.' },
    { h: 'Small corpora, small priority', p: 'Maltese has real academic resources — the Korpus Malti runs to hundreds of millions of tokens, and local models like BERTu exist — but big-tech platform investment follows big markets. Underserved is the precise word.' },
  ],
  flowAlt: 'Abstract render of scattered letterforms flowing into one ordered blue channel — a corpus being built',
  cap: 'META-NET: 21 OF 30 EUROPEAN LANGUAGES RATED WEAK OR UNSUPPORTED — MALTESE LOWEST IN EVERY CATEGORY',
  whoH: 'For the speakers —<br><span class="mute">and the language itself.</span>',
  first: {
    icon: 'globe',
    h: 'Maltese, the home case',
    p: 'VF Empire is a Maltese company. The national language of our own jurisdiction — semitic root, latin script, an official EU language — sits in the lowest support band of European language technology. We build for Maltese first because it is ours, and because if the methods work here they port to every underserved language.',
    co: ['OFFICIAL EU LANGUAGE', 'LOWEST SUPPORT BAND', 'OUR OWN HOME', 'METHODS THAT PORT'],
  },
  aud: [
    { icon: 'users', h: 'Everyday speakers', p: 'Translation and writing assistance that treats the language as a first-class citizen — drafting, correcting and translating with real fluency, not an afterthought model.' },
    { icon: 'book', h: 'Learners & the diaspora', p: 'Emigrant families and second-generation speakers get a serious learning tool — the bridge back to a language that classrooms abroad will never teach.' },
    { icon: 'building', h: 'Institutions & media', p: 'Government, courts, broadcasters and publishers working under official bilingualism get language tooling that actually carries the load in both languages.' },
    { icon: 'heart', h: 'Language communities beyond Malta', p: 'The programme is a template: corpus tooling, training recipes and product patterns designed to be reapplied wherever a community wants its language to have a digital future.' },
  ],
  howH: 'From corpus<br><span class="mute">to living tools.</span>',
  howLead: 'Preservation that matters is not archiving — it is daily usefulness. The measure of the programme is whether speakers reach for the language more because the tools finally work.',
  outs: [
    { h: 'Translation that respects', p: 'Maltese–English and Maltese–EU-language translation built on and evaluated against real corpora — fluency judged by native speakers, not benchmark averages.' },
    { h: 'Learning that connects', p: 'A learner experience built from the corpus outward — real usage, real register, real voice — for students, diaspora and new residents alike.' },
    { h: 'A corpus that compounds', p: 'Community-contributed text and speech, properly licensed and credited, growing the shared foundation every future Maltese tool will stand on.' },
  ],
  mechH: 'Modern methods,<br><span class="mute">pointed at a small language.</span>',
  mechLead: 'Low-resource NLP is a real research field with real techniques — transfer learning, data-efficient fine-tuning, community corpus building. The programme applies them with engineering seriousness, building on the academic work Malta has already done.',
  mechAlt: 'Layered render of a small language corpus being amplified through stacked blue model layers',
  layers: [
    { h: 'The corpus layer', p: 'Building on existing resources — the Korpus Malti tradition, public text, licensed archives — plus community contribution pipelines for text and speech, with clear licensing and credit.' },
    { h: 'The model core', p: 'Data-efficient training: multilingual transfer, fine-tuning on curated Maltese data, evaluation sets built with native speakers. Standing on prior local work such as BERTu, not ignoring it.' },
    { h: 'The tool layer', p: 'Translation, writing assistance, speech interfaces and the learning product — the corpus made useful in daily life, which is what keeps a corpus growing.' },
    { h: 'The template layer', p: 'Everything documented as a repeatable method — so the second language costs a fraction of the first, and communities can bring their own.' },
  ],
  roadH: 'One language done properly,<br><span class="mute">then the method travels.</span>',
  road: [
    { h: 'The Maltese foundation', p: 'Corpus assembly and licensing, first translation and writing models, native-speaker evaluation panels standing.' },
    { h: 'The daily tools', p: 'Public translation and writing assistance, the learning experience, speech in and out — Maltese in the pocket, working.' },
    { h: 'The second language', p: 'The template proven on a second underserved language with a partner community, and institutional offerings for official bilingual workflows.' },
  ],
  paper: { h: 'Infrastructure for small languages', p: 'The VF position paper on low-resource language technology: why market logic fails small languages, and the corpus-first architecture that doesn’t.' },
  repo: { h: 'low-resource-language-ai', p: 'Corpus tooling, training recipes and evaluation sets. The method layer will be open — that is the entire point of building a template.' },
  ctaH: 'Every language deserves<br><span class="mute">a digital future.</span>',
  ctaLead: 'Low-Resource Language AI is in build, Maltese first. Speakers, teachers, linguists, contributors — register interest. Corpus partners shape this from the ground up.',
},

// ─── P·12 CITIZEN SERVICES DESK ──────────────────────────────────────
{
  slug: 'citizen-services-desk',
  name: 'Citizen Services Desk',
  pn: 'P·12',
  sector: 'CIVIC',
  titleTag: 'Municipal AI on the Municipality’s Own Metal',
  metaDesc: 'Citizen Services Desk by VF Empire — permits, forms and citizen queries handled in local language, run by municipalities on infrastructure they control. In build in Malta, EU.',
  ogTitle: 'Public services, on public infrastructure',
  ogDesc: 'A citizen-services AI desk municipalities run on their own metal — local language, local control, European by architecture. On the VF build slate.',
  appCategory: 'BusinessApplication',
  os: 'On-premise, Web',
  ldDesc: 'Citizen Services Desk is a civic-technology system in development by VF Empire Corp Ltd: AI-assisted handling of permits, forms and citizen queries in local languages, deployed on infrastructure that municipalities own and control.',
  img: 'p12',
  tagline: 'Government of the people,<br><em class="i">hosted by the people.</em>',
  sub: 'Citizens meet the state at the town hall, not the ministry — and the town hall is where digital government runs thinnest. Citizen Services Desk gives municipalities an AI service layer for permits, forms and questions, in the local language, on metal the municipality controls.',
  chips: ['SOVEREIGN DEPLOYMENT', 'LOCAL LANGUAGE', 'MUNICIPALITY-SCALE'],
  heroAlt: 'Minimal 3D render of a town hall with one blue-lit doorway — Citizen Services Desk by VF Empire',
  whyH: 'Digital government stops<br><span class="mute">at the town hall door.</span>',
  whyLead: 'National portals modernised; local government — where most citizen contact actually happens — was left with PDF forms, phone queues and shrinking staff. And the sovereignty question underneath got answered under oath.',
  fails: [
    { h: 'The local gap is measured', p: 'The EU’s own eGovernment benchmarking consistently finds local and regional services lagging national ones. Seven in ten EU citizens now use e-government — and hit the thinnest service exactly where they live.' },
    { h: 'Some of Europe is far behind', p: 'Usage tells the spread: while some member states run near-universal digital government, others sit at a quarter to a third of citizens using it. The gap is capacity, not desire — small administrations cannot staff a digital department.' },
    { h: 'Sovereignty was answered under oath', p: 'Asked before the French Senate in 2025 whether it could guarantee French data would never be handed to foreign authorities without EU consent, a Microsoft executive answered that he could not guarantee it. For public administration, that answer is an architecture requirement.' },
    { h: 'The staffing cliff is here', p: 'Germany’s public-service association counts hundreds of thousands of unfilled public-sector posts. The clerks who remain drown in routine queries that software should have absorbed years ago.' },
  ],
  flowAlt: 'Abstract render of citizen request forms flowing through one blue municipal gateway',
  cap: 'ASKED IF EU DATA COULD BE GUARANTEED SAFE FROM FOREIGN HANDOVER: “NO, I CANNOT GUARANTEE IT”',
  whoH: 'For the administrations<br><span class="mute">closest to the citizen.</span>',
  first: {
    icon: 'building',
    h: 'The small municipality',
    p: 'The design customer is a local council of a few thousand to a hundred thousand residents — big enough to drown in queries, too small for a digital department. The Desk arrives as a system, not a project: deployed on their metal, speaking their citizens’ language, run by the staff they already have.',
    co: ['NO IT DEPARTMENT', 'LOCAL-LANGUAGE DUTY', 'SOVEREIGN BY MANDATE', 'STAFF-RUN'],
  },
  aud: [
    { icon: 'users', h: 'Citizens', p: 'Answers about permits, deadlines, documents and procedures — in plain local language, around the clock, with the path to a human clerk always one step away.' },
    { icon: 'briefcase', h: 'Clerks & caseworkers', p: 'The routine query load absorbed, incoming requests arriving pre-structured with complete documents — staff time returned to the cases that need judgement.' },
    { icon: 'globe', h: 'Multilingual communities', p: 'Municipalities serving residents in several languages — Malta’s official bilingualism, border regions, migrant communities — get service parity across all of them.' },
    { icon: 'shield', h: 'Regional governments', p: 'Higher tiers get a deployable pattern: the same sovereign architecture rolled across many municipalities, each keeping its own data on its own infrastructure.' },
  ],
  howH: 'The queue shortens.<br><span class="mute">The data stays home.</span>',
  howLead: 'The Desk automates the routine layer of citizen service and structures the rest for human decision — with every byte processed on infrastructure the administration answers for.',
  outs: [
    { h: 'Questions answered at once', p: 'The bulk of citizen contact is informational — requirements, deadlines, which form, which office. That layer becomes instant, correct and sourced from the municipality’s own rules.' },
    { h: 'Requests arrive complete', p: 'Guided intake that checks documents and requirements before submission — the back-and-forth that consumes clerk weeks engineered out at the front door.' },
    { h: 'Sovereignty by architecture', p: 'On-premise or EU-sovereign hosting under the municipality’s control. The guarantee no foreign cloud could give under oath, delivered structurally instead.' },
  ],
  mechH: 'A civic system,<br><span class="mute">shaped like a utility.</span>',
  mechLead: 'The Desk deploys like municipal equipment: installed on local or sovereign infrastructure, loaded with the municipality’s own rules and procedures, operated by administrative staff through plain interfaces.',
  mechAlt: 'Layered render of civic documents stacking into one blue-sealed municipal core',
  layers: [
    { h: 'The knowledge base', p: 'The municipality’s actual rules — bylaws, fee schedules, procedures, forms — ingested with versioning, so answers cite the current local truth, not a national generality.' },
    { h: 'The service engine', p: 'Retrieval-grounded answering and guided intake flows, multilingual per the community’s real languages, with confidence thresholds that hand uncertain cases to humans.' },
    { h: 'The caseworker surface', p: 'Structured queues, drafted responses for approval, and workload views — clerks supervise the desk; the desk never acts beyond its delegation.' },
    { h: 'The sovereign base', p: 'On-premise or qualified EU hosting, open standards for records, full audit logs. Compatible in spirit with Europe’s sovereign-workplace efforts — and inspectable by the administration that runs it.' },
  ],
  roadH: 'One town hall live,<br><span class="mute">then the pattern spreads.</span>',
  road: [
    { h: 'The first council', p: 'Pilot deployment with a working municipality: knowledge-base ingestion, citizen Q&A and guided intake in production, clerk workflows proven.' },
    { h: 'The service span', p: 'Permit and application processing depth, additional language packs, multi-department coverage, audit and records-management integration.' },
    { h: 'The municipal fleet', p: 'General availability with regional-government rollout patterns, procurement-ready documentation, and a partner network for local deployment.' },
  ],
  paper: { h: 'The last mile of the state', p: 'The VF position paper on municipal AI: why local government is digital government’s hardest and most human tier, and what sovereign deployment actually requires.' },
  repo: { h: 'citizen-services-desk', p: 'Deployment framework and knowledge-base tooling. Public-sector code deserves public scrutiny — core components will be opened as the build matures.' },
  ctaH: 'The town hall deserves<br><span class="mute">the best software in the state.</span>',
  ctaLead: 'Citizen Services Desk is in build. Municipal officers, clerks, regional CIOs — register interest. Pilot councils define the product.',
},

// ─── P·13 CLAIMS ADVOCATE ────────────────────────────────────────────
{
  slug: 'claims-advocate',
  name: 'Claims Advocate',
  pn: 'P·13',
  sector: 'INSURANCE',
  titleTag: 'AI on the Policyholder’s Side',
  metaDesc: 'Claims Advocate by VF Empire — evidence, precedent and persistence for insurance claimants. Insurers run AI on every claim; this levels the table. In build in Malta, EU.',
  ogTitle: 'The insurer brought AI to your claim. Now so do you.',
  ogDesc: 'Evidence assembly, policy analysis and appeal support for insurance claimants — the policyholder’s side of the table, finally equipped. On the VF build slate.',
  appCategory: 'BusinessApplication',
  os: 'Web, iOS, Android',
  ldDesc: 'Claims Advocate is a consumer-support system in development by VF Empire Corp Ltd: evidence organisation, policy analysis and appeal preparation for insurance claimants. It provides information and document support, not legal or regulated claims-management advice, and points users to ombudsman services and qualified professionals where appropriate.',
  img: 'p13',
  tagline: 'They automated the “no”.<br><em class="i">We’re equipping the appeal.</em>',
  sub: 'Insurers assess claims with software, at scale. The policyholder answers with a shoebox of paperwork and an evening of dread. Claims Advocate levels the table — your policy decoded, your evidence organised, your appeal built properly — because the data says appeals win far more often than people file them.',
  chips: ['POLICYHOLDER-SIDE', 'EVIDENCE-FIRST', 'KNOWS THE OMBUDSMAN'],
  heroAlt: 'Minimal 3D render of an umbrella with a blue rim standing firm — Claims Advocate by VF Empire',
  whyH: 'The appeal usually wins.<br><span class="mute">Almost nobody files it.</span>',
  whyLead: 'The most damning numbers in insurance are not the denial rates — they are the appeal rates. The system works for those who push back, and almost no one is equipped to.',
  fails: [
    { h: 'The unfiled appeal', p: 'US marketplace data analysed by KFF shows under 1% of denied in-network claims are appealed — yet where appeals happen, large shares are overturned, in some datasets between four and six-plus out of every ten. The gap between those numbers is the product.' },
    { h: 'Denial at machine speed', p: 'ProPublica reported a major US insurer’s review system enabling denials at an average of 1.2 seconds per claim across hundreds of thousands of claims. Whatever the jurisdiction, the direction is clear: the assessing side is automated.' },
    { h: 'Europe’s numbers agree', p: 'The UK Financial Ombudsman upholds roughly a third of insurance complaints brought to it — higher in some categories. Germany’s BaFin logged a sharp surge in insurance complaints. Pushing back works; people just need the means.' },
    { h: 'The paperwork is the weapon', p: 'Deadlines, evidence formats, policy exclusions in defined terms — the process itself deters claimants. Attrition is not an accident of complexity; complexity is doing its job.' },
  ],
  flowAlt: 'Abstract render of scattered claim documents assembling into one ordered blue case file',
  cap: 'UNDER 1% OF DENIED CLAIMS ARE APPEALED. UP TO TWO-THIRDS OF APPEALS WIN.',
  whoH: 'For the side of the table<br><span class="mute">without a claims department.</span>',
  first: {
    icon: 'shield',
    h: 'The denied policyholder',
    p: 'The first user holds a denial letter and a sense of injustice, and is about to give up. The Advocate’s job is that moment: decode the denial against the actual policy wording, assess what an appeal needs, assemble it properly — and know when the ombudsman is the next stop.',
    co: ['DENIAL IN HAND', 'POLICY UNREAD', 'DEADLINE RUNNING', 'READY TO FOLD'],
  },
  aud: [
    { icon: 'home', h: 'Household & property claims', p: 'Water, storm, fire, burglary — high-document claims where organised evidence and correct process visibly change outcomes.' },
    { icon: 'heart', h: 'Health & disability claimants', p: 'The claims with the highest stakes and the most exhausted claimants — structured support through the process, with professional and advice-service routing where matters exceed a tool.' },
    { icon: 'truck', h: 'Motor & travel claims', p: 'The high-volume everyday disputes — liability arguments, valuation disagreements, trip losses — where a well-assembled file is most of the battle.' },
    { icon: 'briefcase', h: 'Small businesses', p: 'Business-interruption and commercial-property claims, where firms face specialist insurer teams with no in-house counterpart at all.' },
  ],
  howH: 'From shoebox<br><span class="mute">to case file.</span>',
  howLead: 'The Advocate provides information and document support — decoding, organising, drafting for your review. It does not give legal advice, and it tells you plainly when a matter needs an ombudsman, a regulated advisor or a lawyer.',
  outs: [
    { h: 'The policy, decoded', p: 'Your actual wording — cover, exclusions, defined terms, deadlines — explained in plain language against the facts of your claim.' },
    { h: 'The file, built properly', p: 'Evidence collected, ordered and gap-checked into the shape claim handlers process fastest; appeal letters drafted for your approval, grounded in the policy text.' },
    { h: 'The escalation map', p: 'Every jurisdiction’s free routes — internal complaint, ombudsman, regulator — with deadlines tracked and next steps queued. Persistence, systematised.' },
  ],
  mechH: 'Document intelligence,<br><span class="mute">with a compliance spine.</span>',
  mechLead: 'The core is careful document work: reading policies, structuring evidence, drafting correspondence — wrapped in a boundary layer that keeps the tool on the right side of legal-services and claims-management rules in every market it enters.',
  mechAlt: 'Layered render of policy pages compressing into one clear blue case summary',
  layers: [
    { h: 'The policy reader', p: 'Extraction and plain-language explanation of cover, exclusions, conditions and time limits from the policyholder’s own documents — every explanation anchored to the clause it came from.' },
    { h: 'The evidence organiser', p: 'Photos, reports, invoices, correspondence — structured into a chronological, gap-checked case file that both sides of the table can navigate.' },
    { h: 'The drafting engine', p: 'Appeal and complaint correspondence generated from policy text and evidence, always for the claimant’s review and signature — the user speaks; the tool prepares.' },
    { h: 'The boundary layer', p: 'Jurisdiction-aware rules for what the tool may and may not do — with routing to ombudsman schemes, regulated claims professionals and lawyers built in as a feature, not a fallback.' },
  ],
  roadH: 'One claim class proven,<br><span class="mute">then the whole shoebox.</span>',
  road: [
    { h: 'The property core', p: 'Household and property claims in the pilot jurisdictions: policy decoding, case-file assembly and appeal drafting proven on real denials.' },
    { h: 'The full lines', p: 'Motor, travel and health claim support, deadline automation, ombudsman-format exports per jurisdiction.' },
    { h: 'The level table', p: 'General availability across initial EU markets and the UK, small-business claims, and partnerships with consumer-advice organisations.' },
  ],
  paper: { h: 'The asymmetry economy', p: 'The VF position paper on claims asymmetry: what the appeal statistics reveal, and the honest boundaries of a policyholder-side tool.' },
  repo: { h: 'claims-advocate', p: 'Document pipeline and case-file format. The escalation-route directory will be maintained openly — free remedies should be findable by everyone.' },
  ctaH: 'You paid the premiums.<br><span class="mute">Claim like it.</span>',
  ctaLead: 'Claims Advocate is in build. If you hold a denial letter — or fold before appealing — register interest. Real cases shape the pilot.',
},

// ─── P·14 OFFLINE-FIRST RESPONSE ─────────────────────────────────────
{
  slug: 'offline-first-response',
  name: 'Offline-First Response',
  pn: 'P·14',
  sector: 'EMERGENCY',
  titleTag: 'Coordination That Survives the Blackout',
  metaDesc: 'Offline-First Response by VF Empire — emergency coordination systems that keep working when networks don’t. Built for the disasters that take infrastructure down first. In build in Malta, EU.',
  ogTitle: 'Disasters take the network down first',
  ogDesc: 'Emergency coordination built offline-first — local mesh, local state, sync when possible — for the hours when the grid and the towers are gone. On the VF build slate.',
  appCategory: 'UtilitiesApplication',
  os: 'iOS, Android, Field units',
  ldDesc: 'Offline-First Response is an emergency-coordination system in development by VF Empire Corp Ltd: situation tracking, tasking and messaging designed to operate on local networks and device meshes when wide-area connectivity fails, syncing opportunistically when links return.',
  img: 'p14',
  tagline: 'Built for the hour<br><em class="i">the network dies.</em>',
  sub: 'Europe’s recent disasters share one pattern: the communications infrastructure failed exactly when coordination mattered most. Offline-First Response inverts the assumption — a coordination system that treats the network as a bonus, not a dependency.',
  chips: ['WORKS DISCONNECTED', 'LOCAL MESH', 'CIVILIAN-ADMINISTRATION GRADE'],
  heroAlt: 'Minimal 3D render of a beacon tower emitting blue pulse rings — Offline-First Response by VF Empire',
  whyH: 'Every recent disaster<br><span class="mute">wrote the same lesson.</span>',
  whyLead: 'Ahr valley. Valencia. The Iberian blackout. Different catastrophes, one repeated failure class: the systems meant to coordinate response assumed connectivity that the catastrophe itself removed.',
  fails: [
    { h: 'Ahr 2021: the network drowned', p: 'The flood destroyed dozens of switching centres and took mobile coverage with it; alerts reached many residents near midnight, hours behind the water. More than 180 people died. Germany introduced cell-broadcast alerting only in 2023 — after.' },
    { h: 'Valencia 2024: the alert came late', p: 'The ES-Alert message reached phones roughly eight hours after flooding began in parts of the province. 223 people died. The alerting technology existed and worked — activation and coordination failed around it.' },
    { h: 'Iberia 2025: the dependency exposed', p: 'The peninsula-wide blackout took internet traffic down by 80–90%. Operators with battery-backed infrastructure stayed partly up — proving resilience is an engineering choice, made or not made before the event.' },
    { h: 'Coordination tooling assumes the cloud', p: 'Mainstream incident platforms are cloud services. When the towers are dark or the grid is down, the coordination layer vanishes precisely at its moment of purpose. Offline capability must be the foundation, not a degraded mode.' },
  ],
  flowAlt: 'Abstract render of scattered nodes linking into a self-standing blue mesh — coordination without infrastructure',
  cap: 'VALENCIA 2024: THE ALERT ARRIVED ~8 HOURS AFTER THE FLOODING BEGAN. 223 DEAD.',
  whoH: 'For the responders<br><span class="mute">the network abandons.</span>',
  first: {
    icon: 'alert',
    h: 'The municipal crisis team',
    p: 'The first user is the local civil-protection unit — the mayor’s crisis cell, the volunteer fire brigade, the parish flood group. They coordinate the first and worst hours, and they are the least equipped tier: no satcom trucks, no federal systems, just phones that stopped working. The system is built for them.',
    co: ['FIRST HOURS', 'VOLUNTEER-STAFFED', 'NO SPECIAL KIT', 'LOCAL KNOWLEDGE'],
  },
  aud: [
    { icon: 'shield', h: 'Civil-protection agencies', p: 'Regional and national services get an offline-capable common operating picture that municipal tiers can actually feed — because it runs on what those tiers have.' },
    { icon: 'users', h: 'Volunteer organisations', p: 'Fire brigades, rescue services, Red Cross chapters — tasking, status and messaging that keeps working in the field where their work actually happens.' },
    { icon: 'building', h: 'Critical facilities', p: 'Hospitals, utilities, care homes — a resilient status and request channel to their local coordination cell for exactly the hours the phones are down.' },
    { icon: 'globe', h: 'Communities at known risk', p: 'Flood valleys, fire zones, islands — Malta included — where a locally-owned coordination capability is cheap insurance against a well-documented failure mode.' },
  ],
  howH: 'Coordination that degrades<br><span class="mute">gracefully — starting from zero bars.</span>',
  howLead: 'The design baseline is total wide-area failure. Everything works locally first; connectivity, when present, makes it better rather than making it possible.',
  outs: [
    { h: 'A picture without the cloud', p: 'Incidents, resources, road states and needs tracked on a local node and device mesh — the operating picture lives in the room and the field, not in a distant data centre.' },
    { h: 'Tasking that reaches the field', p: 'Assignments and status flowing over device-to-device links and local radio bridges — hop by hop if that is what the day allows.' },
    { h: 'Sync when the world returns', p: 'When any link appears — one bar, one satellite terminal, one restored mast — state reconciles outward automatically. Nothing waits for connectivity; everything uses it.' },
  ],
  mechH: 'Local node, device mesh,<br><span class="mute">opportunistic everything.</span>',
  mechLead: 'The architecture is a hierarchy of survivable layers: hardened local nodes, phone-to-phone meshing, bridges to whatever radio or satellite links exist — with a data model built for disconnection and merge from the first line of code.',
  mechAlt: 'Layered render of a beacon core with concentric blue rings reaching outlying nodes',
  layers: [
    { h: 'The field layer', p: 'Responder phones running the full app offline — capture, tasking, messaging — meshing device-to-device where platform capabilities allow, storing and forwarding where they don’t.' },
    { h: 'The local node', p: 'A battery-backed unit at the coordination point: local Wi-Fi island, state authority, map and data server. The crisis room works because this box works — and this box needs nothing upstream.' },
    { h: 'The bridge layer', p: 'Connectors to what emergency services already trust — digital radio, amateur bridges, satellite terminals — treated as transport of opportunity, never as dependency.' },
    { h: 'The sync fabric', p: 'A conflict-free data model designed for partition and merge: every node holds usable truth, and any restored link reconciles state without human deduplication.' },
  ],
  roadH: 'Exercised before needed —<br><span class="mute">that is the whole discipline.</span>',
  road: [
    { h: 'The local node', p: 'Core offline coordination: node hardware and software, field app with store-and-forward, the crisis-room picture proven in exercises with a real civil-protection unit.' },
    { h: 'The mesh season', p: 'Device-to-device transports hardened per platform, radio and satellite bridges, multi-node synchronisation across a dispersed incident.' },
    { h: 'The standing capability', p: 'Deployment programmes for municipalities and volunteer organisations, training and exercise packages, and integration with national alerting where interfaces exist.' },
  ],
  paper: { h: 'Assume the network is gone', p: 'The VF position paper on resilient coordination: the failure record from Ahr to the Iberian blackout, and the offline-first architecture it demands.' },
  repo: { h: 'offline-first-response', p: 'Sync fabric and node software. Resilience infrastructure earns trust by being inspectable — core protocols will be open.' },
  ctaH: 'The next one is coming.<br><span class="mute">Coordinate anyway.</span>',
  ctaLead: 'Offline-First Response is in build. Civil-protection officers, brigade leads, resilience planners — register interest. Exercise partners shape the system.',
},

// ─── P·16 VF MAIL ────────────────────────────────────────────────────
{
  slug: 'vf-mail',
  name: 'VF Mail',
  pn: 'P·16',
  sector: 'EMAIL',
  titleTag: 'A Whole Mail System of Our Own',
  metaDesc: 'VF Mail by VF Empire — server, shield and address on metal we hold. The first @vfempire.com inboxes already run on our own node. Your inbox stops being an ad company’s product. In build in Malta, EU.',
  ogTitle: 'Your inbox is someone’s product. Take it back.',
  ogDesc: 'A complete mail system — server, deliverability shield, address — running on owned infrastructure. First light already: our own company mail runs on it. On the VF build slate.',
  appCategory: 'CommunicationApplication',
  os: 'Web, iOS, Android, IMAP/SMTP',
  ldDesc: 'VF Mail is an email system in development by VF Empire Corp Ltd: a complete mail stack — server, security shield and addresses — operated on company-held infrastructure, currently carrying VF Empire’s own corporate mail as its first deployment.',
  img: 'p16',
  tagline: 'Server. Shield. Address.<br><em class="i">All of it yours.</em>',
  sub: 'Email became a duopoly renting you an address inside an advertising ecosystem. VF Mail is the other path: a complete mail system — server, deliverability shield and address — on metal we hold. It is not a plan; the first @vfempire.com inboxes already run on our own node.',
  chips: ['FIRST LIGHT — LIVE ON OUR NODE', 'OWN METAL', 'EU JURISDICTION'],
  heroAlt: 'Minimal 3D render of an envelope monolith with a blue wax seal — VF Mail by VF Empire',
  whyH: 'Two companies read<br><span class="mute">the world’s morning mail.</span>',
  whyLead: 'The most personal document stream in your life — contracts, medical letters, passwords resets, love and grief — flows through infrastructure owned by a handful of firms whose business model is knowing you. Leaving is technically possible and practically punished.',
  fails: [
    { h: 'The concentration is near-total', p: 'Gmail alone is estimated at around two billion accounts, and industry measurements attribute roughly three-quarters of all email opens to just Apple’s and Google’s mail clients. Email is a protocol; the inbox became an oligopoly.' },
    { h: 'Inside the ad machine', p: 'Google stopped scanning Gmail content for ad targeting in 2017 — but the inbox still lives inside an advertising company’s ecosystem, feeding an identity that follows you across every property. The mail is the moat.' },
    { h: 'Independence is punished', p: 'Run your own server by the book — SPF, DKIM, DMARC, clean lists — and the big providers may spam-folder you anyway, because your IP has no history with them. The deliverability wall is the real lock-in, and it is undocumented by design.' },
    { h: 'Privacy mail proved the demand', p: 'Proton grew past a hundred million accounts on the promise of mail outside the ad economy. The demand is proven — what is missing is the full-system offer: not just an encrypted inbox, but the whole stack, owned.' },
  ],
  flowAlt: 'Abstract render of mail envelopes flowing through one blue-sealed gateway — the owned mail path',
  cap: 'TWO COMPANIES’ MAIL CLIENTS HANDLE ROUGHLY THREE-QUARTERS OF THE WORLD’S EMAIL OPENS',
  whoH: 'For everyone whose mail<br><span class="mute">should answer to them.</span>',
  first: {
    icon: 'briefcase',
    h: 'Our own companies — already live',
    p: 'VF Mail carries VF Empire’s corporate mail today: the first @vfempire.com inboxes run on our own node, on our own metal. Dogfood first is house law — the system earns the right to carry your mail by carrying ours through every rough edge first.',
    co: ['FIRST LIGHT LIVE', '@VFEMPIRE.COM ON-NODE', 'OUR METAL', 'HOUSE LAW: DOGFOOD FIRST'],
  },
  aud: [
    { icon: 'users', h: 'Individuals leaving the duopoly', p: 'A real address on real infrastructure with EU jurisdiction — your correspondence outside any advertising identity, without becoming your own sysadmin.' },
    { icon: 'building', h: 'Small companies', p: 'Company mail on company terms: custom domain, team inboxes, and a provider whose business model is the service fee — not the metadata.' },
    { icon: 'shield', h: 'Confidentiality professions', p: 'Lawyers, doctors, accountants, journalists — professions whose correspondence carries duties that sit uneasily inside foreign ad-tech ecosystems.' },
    { icon: 'globe', h: 'Sovereignty-minded organisations', p: 'NGOs, associations and public-adjacent bodies that want their mail under European law on inspectable infrastructure.' },
  ],
  howH: 'The whole stack,<br><span class="mute">not another app on theirs.</span>',
  howLead: 'Most “private email” is a client on someone else’s cloud. VF Mail is the full system — transport, storage, shield and interface — with the hard part, deliverability, run as a managed discipline so you never fight that war yourself.',
  outs: [
    { h: 'An address that answers to you', p: 'Your mail on infrastructure we hold and you can leave — full export, standard protocols, no hostage data. Ownership means the door opens from the inside.' },
    { h: 'The reputation war, handled', p: 'Warmed IPs, strict authentication, feedback loops, blocklist vigilance — we run the deliverability battle for you as an operations discipline. That is the product’s hardest promise, stated honestly: run, not magically solved.' },
    { h: 'A shield on the front door', p: 'Spam and phishing defence at the server, aggressive transport encryption, and none of the engagement machinery — no ads, no tracking pixels of our own, no profile built from your correspondence.' },
  ],
  mechH: 'Modern stack,<br><span class="mute">old-school ownership.</span>',
  mechLead: 'The build stands on the modern self-hosted mail generation — hardened, memory-safe server software on clean-IP metal — wrapped in the operational layer that makes owned mail practical for people with lives.',
  mechAlt: 'Layered render of a mail server monolith with one blue seal of authentication',
  layers: [
    { h: 'The transport core', p: 'A modern, memory-safe mail server stack — the Stalwart generation of software — on clean-reputation infrastructure in EU jurisdiction, with full standards compliance: SPF, DKIM, DMARC, MTA-STS, DANE.' },
    { h: 'The shield layer', p: 'Inbound filtering, phishing and malware defence, and outbound reputation protection — the security department every mail admin wishes they had, built into the service.' },
    { h: 'The reputation operation', p: 'IP warming, deliverability monitoring, blocklist response and provider-relations discipline, run continuously. This layer is why owned mail usually fails — and why VF Mail is an operated system, not a software download.' },
    { h: 'The inbox surface', p: 'Clean web and mobile clients plus full IMAP/SMTP for any client you prefer — an interface in the house style: quiet, fast, and structurally incapable of advertising to you.' },
  ],
  roadH: 'Company mail first.<br><span class="mute">Then yours.</span>',
  road: [
    { h: 'First light — our own mail', p: 'The VF group’s corporate mail live on the owned node — real correspondence, real deliverability battles, the operations playbook written from experience.' },
    { h: 'The hardened node', p: 'Multi-domain hosting, the shield layer completed, client apps polished, migration tooling from the major providers proven on willing pilots.' },
    { h: 'The open door', p: 'General availability for individuals and companies: addresses, custom domains and team mail on VF-held infrastructure — the inbox as a service you own, not a product you are.' },
  ],
  paper: { h: 'The owned inbox', p: 'The VF position paper on mail sovereignty: the deliverability wall, the concentration numbers, and the operations discipline that makes independent mail viable.' },
  repo: { h: 'vf-mail', p: 'Deployment configurations and shield tooling around the open-source mail core. What we harden, we document — the independent-mail ecosystem wins together.' },
  ctaH: 'Your mail. Your metal.<br><span class="mute">Our watch.</span>',
  ctaLead: 'VF Mail has first light — our own company mail runs on it now. If you want your inbox back when the doors open, register interest. Early pilots migrate first.',
},

];
