// VF systems pages: content pack C: P·11–P·14 + P·16.
// Grounded on research pack C (2026-09-11). Honesty law applies: no invented stats, guardrails obeyed.

export default [

// ─── P·11 LOW-RESOURCE LANGUAGE AI ───────────────────────────────────
{
  slug: 'low-resource-language-ai',
  name: 'Low-Resource Language AI',
  pn: 'P·11',
  sector: 'LANGUAGE',
  titleTag: 'AI for small languages',
  metaDesc: 'Low-Resource Language AI by VF Empire: translation, learning and preservation tools for underserved languages, Maltese first. In build in Malta, EU.',
  ogTitle: 'Seven thousand languages. AI speaks a few hundred.',
  ogDesc: 'Translation, learning and preservation infrastructure for the languages underserved by big-tech platforms, starting with Maltese. On the VF build slate.',
  appCategory: 'UtilitiesApplication',
  os: 'Web, iOS, Android',
  ldDesc: 'Low-Resource Language AI is a language-technology programme in development by VF Empire Corp Ltd: translation, language learning and preservation tooling for languages underserved by mainstream AI platforms, beginning with Maltese.',
  img: 'p11',
  tagline: 'A language dies quietly.<br><em class="i">Or it gets infrastructure.</em>',
  sub: 'Google Translate covers roughly 249 of the world’s ~7,000 languages. The rest, including most of Europe’s smaller tongues, live outside the AI era looking in. This programme builds the missing infrastructure, starting with the language of our own home: Maltese.',
  chips: ['MALTESE FIRST', 'PRESERVATION-GRADE', 'COMMUNITY CORPUS'],
  heroAlt: 'Minimal 3D render of speech bubbles with one small blue bubble among them: Low-Resource Language AI by VF Empire',
  whyH: 'The digital age has a language policy.<br><span class="mute">Nobody voted for it.</span>',
  whyLead: 'Market size decides which languages get AI. The result is a quiet sorting of the world’s languages into those with a digital future and those without.',
  fails: [
    { h: 'Coverage is a rounding error', p: 'Around 249 languages on Google Translate, out of roughly 7,000 spoken. Researcher András Kornai estimated fewer than 5% of languages are ascending into digital use at all; the rest are digitally static or sinking.' },
    { h: 'Europe is not exempt', p: 'The META-NET studies rated 21 of 30 European languages as having weak or no support in key language-technology areas. Maltese, an official EU language, scored in the lowest band in every category studied.' },
    { h: 'Endangerment is accelerating', p: 'UNESCO estimates around 40% of the world’s languages are endangered. Digital absence compounds it: a language your phone cannot speak is a language your children practise less.' },
    { h: 'Small corpora, small priority', p: 'Maltese has real academic resources (the Korpus Malti runs to hundreds of millions of tokens, and local models like BERTu exist), but big-tech platform investment follows big markets. Underserved is the precise word.' },
  ],
  flowAlt: 'Abstract render of scattered letterforms flowing into one ordered blue channel, a corpus being built',
  cap: 'META-NET: 21 OF 30 EUROPEAN LANGUAGES RATED WEAK OR UNSUPPORTED. MALTESE LOWEST IN EVERY CATEGORY',
  whoH: 'For the speakers,<br><span class="mute">and the language itself.</span>',
  first: {
    icon: 'globe',
    h: 'Maltese, the home case',
    p: 'VF Empire is a Maltese company. The national language of our own jurisdiction (semitic root, latin script, an official EU language) sits in the lowest support band of European language technology. We build for Maltese first because it is ours, and because if the methods work here they port to other underserved languages.',
    co: ['OFFICIAL EU LANGUAGE', 'LOWEST SUPPORT BAND', 'OUR OWN HOME', 'METHODS THAT PORT'],
  },
  aud: [
    { icon: 'users', h: 'Everyday speakers', p: 'Translation and writing assistance that treats the language as a first-class citizen: drafting, correcting and translating with real fluency.' },
    { icon: 'book', h: 'Learners & the diaspora', p: 'Emigrant families and second-generation speakers get a serious learning tool, the bridge back to a language that classrooms abroad do not teach.' },
    { icon: 'building', h: 'Institutions & media', p: 'Government, courts, broadcasters and publishers working under official bilingualism get language tooling that carries the load in both languages.' },
    { icon: 'heart', h: 'Language communities beyond Malta', p: 'The programme is a template: corpus tooling, training recipes and product patterns designed to be reapplied wherever a community wants its language to have a digital future.' },
  ],
  howH: 'From corpus<br><span class="mute">to living tools.</span>',
  howLead: 'Preservation that matters is daily usefulness. The measure of the programme is whether speakers reach for the language more because the tools work.',
  outs: [
    { h: 'Translation that respects', p: 'Maltese–English and Maltese–EU-language translation built on and evaluated against real corpora, with fluency judged by native speakers.' },
    { h: 'Learning that connects', p: 'A learner experience built from the corpus outward (real usage, real register, real voice) for students, diaspora and new residents alike.' },
    { h: 'A corpus that compounds', p: 'Community-contributed text and speech, properly licensed and credited, growing the shared foundation future Maltese tools will stand on.' },
  ],
  mechH: 'Modern methods,<br><span class="mute">pointed at a small language.</span>',
  mechLead: 'Low-resource NLP is a real research field with real techniques: transfer learning, data-efficient fine-tuning, community corpus building. The programme applies them with engineering seriousness, building on the academic work Malta has already done.',
  mechAlt: 'Layered render of a small language corpus being amplified through stacked blue model layers',
  layers: [
    { h: 'The corpus layer', p: 'Building on existing resources (the Korpus Malti tradition, public text, licensed archives) plus community contribution pipelines for text and speech, with clear licensing and credit.' },
    { h: 'The model core', p: 'Data-efficient training: multilingual transfer, fine-tuning on curated Maltese data, evaluation sets built with native speakers. Standing on prior local work such as BERTu.' },
    { h: 'The tool layer', p: 'Translation, writing assistance, speech interfaces and the learning product: the corpus made useful in daily life, which is what keeps it growing.' },
    { h: 'The template layer', p: 'Everything documented as a repeatable method, so the second language costs a fraction of the first and communities can bring their own.' },
  ],
  roadH: 'One language done properly,<br><span class="mute">then the method travels.</span>',
  road: [
    { h: 'The Maltese foundation', p: 'Corpus assembly and licensing, first translation and writing models, native-speaker evaluation panels standing.' },
    { h: 'The daily tools', p: 'Public translation and writing assistance, the learning experience, speech in and out: Maltese in the pocket, working.' },
    { h: 'The second language', p: 'The template proven on a second underserved language with a partner community, and institutional offerings for official bilingual workflows.' },
  ],
  paper: { h: 'Infrastructure for small languages', p: 'The VF position paper on low-resource language technology: why market logic fails small languages, and the corpus-first architecture built to serve them.' },
  repo: { h: 'low-resource-language-ai', p: 'Corpus tooling, training recipes and evaluation sets. The method layer will be open; that is the entire point of building a template.' },
  ctaH: 'Every language deserves<br><span class="mute">a digital future.</span>',
  ctaLead: 'Low-Resource Language AI is in build, Maltese first. Speakers, teachers, linguists, contributors: register interest. Corpus partners shape this from the ground up.',
  faq: [
    { q: 'Which languages does it cover?', a: 'Maltese first. VF Empire is a Maltese company and the national language sits in the lowest support band of European language technology. Everything is documented as a repeatable method, so the template is proven next on a second underserved language with a partner community, and communities can bring their own.' },
    { q: 'What tools will it offer?', a: 'Maltese to English and Maltese to EU-language translation evaluated by native speakers, writing assistance that drafts and corrects, speech in and out, and a learning experience built from the corpus outward for students, the diaspora and new residents. Institutions working under official bilingualism get tooling that carries the load in both languages.' },
    { q: 'How does the corpus get built?', a: 'On existing resources (the Korpus Malti tradition, public text, licensed archives) plus community contribution pipelines for text and speech, with clear licensing and credit. The model core uses data-efficient training: multilingual transfer, fine-tuning on curated Maltese data and evaluation sets built with native speakers, standing on prior local work such as BERTu.' },
    { q: 'Can I contribute?', a: 'Yes. Speakers, teachers, linguists and contributors are invited to register interest, and corpus partners shape the programme from the ground up. Contributed text and speech is properly licensed and credited, growing the shared foundation that future Maltese tools will stand on. The method layer will be open.' },
    { q: 'When does it ship?', a: 'Low-Resource Language AI is in build. The Maltese foundation comes first: corpus assembly and licensing, first translation and writing models, and native-speaker evaluation panels. The daily tools phase brings public translation and writing assistance, the learning experience and speech. The second language and institutional offerings for bilingual workflows follow.' },
  ],
  related: ['citizen-services-desk', 'different-minds-engine'],
},

// ─── P·12 CITIZEN SERVICES DESK ──────────────────────────────────────
{
  slug: 'citizen-services-desk',
  name: 'Citizen Services Desk',
  pn: 'P·12',
  sector: 'CIVIC',
  titleTag: 'Sovereign municipal AI',
  metaDesc: 'Citizen Services Desk by VF Empire: municipal AI for permits, forms and citizen queries, run on infrastructure the council controls. In build in Malta, EU.',
  ogTitle: 'public services, on public infrastructure',
  ogDesc: 'A citizen-services AI desk municipalities run on their own metal: local language, local control, European by architecture. On the VF build slate.',
  appCategory: 'BusinessApplication',
  os: 'On-premise, Web',
  ldDesc: 'Citizen Services Desk is a civic-technology system in development by VF Empire Corp Ltd: AI-assisted handling of permits, forms and citizen queries in local languages, deployed on infrastructure that municipalities own and control.',
  img: 'p12',
  tagline: 'Government of the people,<br><em class="i">hosted by the people.</em>',
  sub: 'Citizens meet the state at the town hall, and the town hall is where digital government runs thinnest. Citizen Services Desk gives municipalities an AI service layer for permits, forms and questions, in the local language, on metal the municipality controls.',
  chips: ['SOVEREIGN DEPLOYMENT', 'LOCAL LANGUAGE', 'MUNICIPALITY-SCALE'],
  heroAlt: 'Minimal 3D render of a town hall with one blue-lit doorway: Citizen Services Desk by VF Empire',
  whyH: 'Digital government stops<br><span class="mute">at the town hall door.</span>',
  whyLead: 'National portals modernised. Local government, where most citizen contact happens, kept its PDF forms, phone queues and shrinking staff. And the sovereignty question underneath got answered under oath.',
  fails: [
    { h: 'The local gap is measured', p: 'The EU’s own eGovernment benchmarking consistently finds local and regional services lagging national ones. Seven in ten EU citizens now use e-government, and hit the thinnest service where they live.' },
    { h: 'Some of Europe is far behind', p: 'Usage tells the spread: some member states run near-universal digital government, others sit at a quarter to a third of citizens using it. The gap is capacity: small administrations cannot staff a digital department.' },
    { h: 'Sovereignty was answered under oath', p: 'Asked before the French Senate in 2025 whether it could guarantee French data would never be handed to foreign authorities without EU consent, a Microsoft executive answered that he could not guarantee it. For public administration, that answer is an architecture requirement.' },
    { h: 'The staffing cliff is here', p: 'Germany’s public-service association counts hundreds of thousands of unfilled public-sector posts. The clerks who remain drown in routine queries that software should have absorbed years ago.' },
  ],
  flowAlt: 'Abstract render of citizen request forms flowing through one blue municipal gateway',
  cap: 'ASKED IF EU DATA COULD BE GUARANTEED SAFE FROM FOREIGN HANDOVER: “NO, I CANNOT GUARANTEE IT”',
  whoH: 'For the administrations<br><span class="mute">closest to the citizen.</span>',
  first: {
    icon: 'building',
    h: 'The small municipality',
    p: 'The design customer is a local council of a few thousand to a hundred thousand residents: big enough to drown in queries, too small for a digital department. The Desk arrives as a system, deployed on their metal, speaking their citizens’ language, run by the staff they already have.',
    co: ['NO IT DEPARTMENT', 'LOCAL-LANGUAGE DUTY', 'SOVEREIGN BY MANDATE', 'STAFF-RUN'],
  },
  aud: [
    { icon: 'users', h: 'Citizens', p: 'Answers about permits, deadlines, documents and procedures in plain local language, around the clock, with the path to a human clerk always one step away.' },
    { icon: 'briefcase', h: 'Clerks & caseworkers', p: 'The Desk absorbs the routine query load and delivers incoming requests pre-structured with complete documents, so staff time goes back to the cases that need judgement.' },
    { icon: 'globe', h: 'Multilingual communities', p: 'Municipalities serving residents in several languages (Malta’s official bilingualism, border regions, migrant communities) get service parity across all of them.' },
    { icon: 'shield', h: 'Regional governments', p: 'Higher tiers get a deployable pattern: the same sovereign architecture rolled across many municipalities, each keeping its own data on its own infrastructure.' },
  ],
  howH: 'The queue shortens.<br><span class="mute">The data stays home.</span>',
  howLead: 'The Desk automates the routine layer of citizen service and structures the rest for human decision, with every byte processed on infrastructure the administration answers for.',
  outs: [
    { h: 'Questions answered at once', p: 'The bulk of citizen contact is informational: requirements, deadlines, which form, which office. The Desk answers that layer at once, correctly, sourced from the municipality’s own rules.' },
    { h: 'Requests arrive complete', p: 'Guided intake checks documents and requirements before submission, removing at the front door the back-and-forth that consumes clerk weeks.' },
    { h: 'Sovereignty by architecture', p: 'On-premise or EU-sovereign hosting under the municipality’s control: the architecture delivers the guarantee no foreign cloud could give under oath.' },
  ],
  mechH: 'A civic system,<br><span class="mute">shaped like a utility.</span>',
  mechLead: 'The Desk deploys like municipal equipment: installed on local or sovereign infrastructure, loaded with the municipality’s own rules and procedures, operated by administrative staff through plain interfaces.',
  mechAlt: 'Layered render of civic documents stacking into one blue-sealed municipal core',
  layers: [
    { h: 'The knowledge base', p: 'The municipality’s own rules (bylaws, fee schedules, procedures, forms), ingested with versioning, so answers cite the current local text.' },
    { h: 'The service engine', p: 'Retrieval-grounded answering and guided intake flows, multilingual per the community’s real languages, with confidence thresholds that hand uncertain cases to humans.' },
    { h: 'The caseworker surface', p: 'Structured queues, drafted responses for approval, and workload views. Clerks supervise the desk; the desk never acts beyond its delegation.' },
    { h: 'The sovereign base', p: 'On-premise or qualified EU hosting, open standards for records, full audit logs. Compatible in spirit with Europe’s sovereign-workplace efforts, and inspectable by the administration that runs it.' },
  ],
  roadH: 'One town hall live,<br><span class="mute">then the pattern spreads.</span>',
  road: [
    { h: 'The first council', p: 'Pilot deployment with a working municipality: knowledge-base ingestion, citizen Q&A and guided intake in production, clerk workflows proven.' },
    { h: 'The service span', p: 'Permit and application processing depth, additional language packs, multi-department coverage, audit and records-management integration.' },
    { h: 'The municipal fleet', p: 'General availability with regional-government rollout patterns, procurement-ready documentation, and a partner network for local deployment.' },
  ],
  paper: { h: 'The last mile of the state', p: 'The VF position paper on municipal AI: why local government is digital government’s hardest and most human tier, and what sovereign deployment requires.' },
  repo: { h: 'citizen-services-desk', p: 'Deployment framework and knowledge-base tooling. Public-sector code deserves public scrutiny; VF will open core components as the build matures.' },
  ctaH: 'The town hall deserves<br><span class="mute">the best software in the state.</span>',
  ctaLead: 'Citizen Services Desk is in build. Municipal officers, clerks and regional CIOs: register interest. Pilot councils define the product.',
  faq: [
    { q: 'Where does citizen data go?', a: 'It stays under the municipality’s control. The Desk runs on-premise or on qualified EU-sovereign hosting, with open standards for records and full audit logs, inspectable by the administration that runs it. Every byte is processed on infrastructure the administration answers for, which delivers the guarantee no foreign cloud could give under oath.' },
    { q: 'Which languages does it support?', a: 'The community’s real languages. The service engine is multilingual per municipality, so councils serving residents in several languages (Malta’s official bilingualism, border regions, migrant communities) get service parity across all of them. Additional language packs arrive in the service span phase of the roadmap.' },
    { q: 'What does the Desk do for citizens?', a: 'Answers about permits, deadlines, documents and procedures in plain local language, around the clock, sourced from the municipality’s own rules. Guided intake checks documents and requirements before submission so requests arrive complete. The path to a human clerk is always one step away.' },
    { q: 'Does it replace clerks?', a: 'No. It absorbs the routine query load and delivers requests pre-structured with complete documents, so staff time goes back to cases that need judgement. Clerks supervise the desk through structured queues, drafted responses for approval and workload views. Confidence thresholds hand uncertain cases to humans; the desk never acts beyond its delegation.' },
    { q: 'Which councils is it built for?', a: 'A local council of a few thousand to a hundred thousand residents: big enough to drown in queries, too small for a digital department. It deploys like municipal equipment, loaded with the council’s own bylaws, fee schedules, procedures and forms, operated by existing staff. Regional governments get a pattern to roll across many municipalities.' },
    { q: 'When does it ship?', a: 'Citizen Services Desk is in build. The first council phase is a pilot deployment with a working municipality: knowledge-base ingestion, citizen Q&A and guided intake in production, clerk workflows proven. Permit-processing depth, language packs and records integration follow, then general availability with procurement-ready documentation. Pilot councils define the product.' },
  ],
  related: ['everyday-law-navigator', 'low-resource-language-ai', 'offline-first-response'],
},

// ─── P·13 CLAIMS ADVOCATE ────────────────────────────────────────────
{
  slug: 'claims-advocate',
  name: 'Claims Advocate',
  pn: 'P·13',
  sector: 'INSURANCE',
  titleTag: 'AI on the policyholder’s side',
  metaDesc: 'Claims Advocate by VF Empire: policy decoding, evidence files and appeal drafting for insurance claimants, ombudsman routes mapped. In build in Malta, EU.',
  ogTitle: 'the insurer brought AI to your claim. Now so do you.',
  ogDesc: 'Evidence assembly, policy analysis and appeal support for insurance claimants: the policyholder’s side of the table, equipped at last. On the VF build slate.',
  appCategory: 'BusinessApplication',
  os: 'Web, iOS, Android',
  ldDesc: 'Claims Advocate is a consumer-support system in development by VF Empire Corp Ltd: evidence organisation, policy analysis and appeal preparation for insurance claimants. It provides information and document support, not legal or regulated claims-management advice, and points users to ombudsman services and qualified professionals where appropriate.',
  img: 'p13',
  tagline: 'They automated the “no”.<br><em class="i">We’re equipping the appeal.</em>',
  sub: 'Insurers assess claims with software, at scale. The policyholder answers with a shoebox of paperwork and an evening of dread. Claims Advocate levels the table: your policy decoded, your evidence organised, your appeal built properly. The data says appeals win far more often than people file them.',
  chips: ['POLICYHOLDER-SIDE', 'EVIDENCE-FIRST', 'KNOWS THE OMBUDSMAN'],
  heroAlt: 'Minimal 3D render of an umbrella with a blue rim standing firm: Claims Advocate by VF Empire',
  whyH: 'The appeal usually wins.<br><span class="mute">Almost nobody files it.</span>',
  whyLead: 'The most damning numbers in insurance are the appeal rates. The system works for those who push back, and almost no one is equipped to.',
  fails: [
    { h: 'The unfiled appeal', p: 'US marketplace data analysed by KFF shows claimants appeal under 1% of denied in-network claims. Where they do, a large share of appeals succeed, in some datasets between four and six-plus out of every ten. The gap between those numbers is the product.' },
    { h: 'Denial at machine speed', p: 'ProPublica reported a major US insurer’s review system enabling denials at an average of 1.2 seconds per claim across hundreds of thousands of claims. In any jurisdiction, the direction is clear: the assessing side is automated.' },
    { h: 'Europe’s numbers agree', p: 'The UK Financial Ombudsman upholds roughly a third of insurance complaints brought to it, higher in some categories. Germany’s BaFin logged a sharp surge in insurance complaints. Pushing back works; people need the means.' },
    { h: 'The paperwork is the weapon', p: 'Deadlines, evidence formats, policy exclusions in defined terms: the process itself deters claimants, and the attrition is the point.' },
  ],
  flowAlt: 'Abstract render of scattered claim documents assembling into one ordered blue case file',
  cap: 'UNDER 1% OF DENIED CLAIMS ARE APPEALED. UP TO TWO-THIRDS OF APPEALS WIN.',
  whoH: 'For the side of the table<br><span class="mute">without a claims department.</span>',
  first: {
    icon: 'shield',
    h: 'The denied policyholder',
    p: 'The first user holds a denial letter and a sense of injustice, and is about to give up. The Advocate’s job is that moment: decode the denial against the actual policy wording, assess what an appeal needs, assemble it properly, and know when the ombudsman is the next stop.',
    co: ['DENIAL IN HAND', 'POLICY UNREAD', 'DEADLINE RUNNING', 'READY TO FOLD'],
  },
  aud: [
    { icon: 'home', h: 'Household & property claims', p: 'Water, storm, fire, burglary: high-document claims where organised evidence and correct process change outcomes.' },
    { icon: 'heart', h: 'Health & disability claimants', p: 'The claims with the highest stakes and the most exhausted claimants get structured support through the process, with routing to professionals and advice services where matters exceed a tool.' },
    { icon: 'truck', h: 'Motor & travel claims', p: 'The high-volume everyday disputes (liability arguments, valuation disagreements, trip losses) where a well-assembled file is most of the battle.' },
    { icon: 'briefcase', h: 'Small businesses', p: 'Business-interruption and commercial-property claims, where firms face specialist insurer teams with no in-house counterpart at all.' },
  ],
  howH: 'From shoebox<br><span class="mute">to case file.</span>',
  howLead: 'The Advocate provides information and document support: decoding, organising, drafting for your review. It does not give legal advice, and it tells you plainly when a matter needs an ombudsman, a regulated advisor or a lawyer.',
  outs: [
    { h: 'The policy, decoded', p: 'Your own wording (cover, exclusions, defined terms, deadlines) explained in plain language against the facts of your claim.' },
    { h: 'The file, built properly', p: 'The Advocate collects, orders and gap-checks your evidence into the shape claim handlers process fastest, and drafts appeal letters for your approval, grounded in the policy text.' },
    { h: 'The escalation map', p: 'The Advocate tracks the deadlines and queues the next step along each jurisdiction’s free routes: internal complaint, ombudsman, regulator.' },
  ],
  mechH: 'Document intelligence,<br><span class="mute">with a compliance spine.</span>',
  mechLead: 'The core is careful document work (reading policies, structuring evidence, drafting correspondence) wrapped in a boundary layer that keeps the tool on the right side of legal-services and claims-management rules in each market it enters.',
  mechAlt: 'Layered render of policy pages compressing into one clear blue case summary',
  layers: [
    { h: 'The policy reader', p: 'Extraction and plain-language explanation of cover, exclusions, conditions and time limits from the policyholder’s own documents, with each explanation anchored to the clause it came from.' },
    { h: 'The evidence organiser', p: 'Photos, reports, invoices and correspondence, structured into a chronological, gap-checked case file that both sides of the table can read.' },
    { h: 'The drafting engine', p: 'Appeal and complaint correspondence generated from policy text and evidence, always for the claimant’s review and signature. The tool prepares; the claimant speaks.' },
    { h: 'The boundary layer', p: 'Jurisdiction-aware rules for what the tool may and may not do, with routing to ombudsman schemes, regulated claims professionals and lawyers built in as a feature.' },
  ],
  roadH: 'One claim class proven,<br><span class="mute">then the whole shoebox.</span>',
  road: [
    { h: 'The property core', p: 'Household and property claims in the pilot jurisdictions: policy decoding, case-file assembly and appeal drafting proven on real denials.' },
    { h: 'The full lines', p: 'Motor, travel and health claim support, deadline automation, ombudsman-format exports per jurisdiction.' },
    { h: 'The level table', p: 'General availability across initial EU markets and the UK, small-business claims, and partnerships with consumer-advice organisations.' },
  ],
  paper: { h: 'The asymmetry economy', p: 'The VF position paper on claims asymmetry: what the appeal statistics reveal, and the honest boundaries of a policyholder-side tool.' },
  repo: { h: 'claims-advocate', p: 'Document pipeline and case-file format. VF will maintain the escalation-route directory in the open; free remedies should be findable by anyone.' },
  ctaH: 'You paid the premiums.<br><span class="mute">Claim like it.</span>',
  ctaLead: 'Claims Advocate is in build. If you hold a denial letter, or fold before appealing, register interest. Real cases shape the pilot.',
  faq: [
    { q: 'Is Claims Advocate legal advice?', a: 'No. It provides information and document support: decoding, organising and drafting for your review. A jurisdiction-aware boundary layer keeps the tool on the right side of legal-services and claims-management rules in each market, and it tells you plainly when a matter needs an ombudsman, a regulated advisor or a lawyer.' },
    { q: 'What does it do with my denial letter?', a: 'It decodes the denial against your actual policy wording: cover, exclusions, defined terms and deadlines explained in plain language, each explanation anchored to the clause it came from. It then assesses what an appeal needs, assembles your evidence into a chronological, gap-checked case file and drafts appeal letters for your approval.' },
    { q: 'Which claims does it cover?', a: 'Household and property claims first: water, storm, fire, burglary. Motor, travel and health claim support follow, then small-business claims such as business interruption and commercial property. Health and disability claimants get structured support with routing to professionals and advice services where matters exceed a tool.' },
    { q: 'Does it know the ombudsman route?', a: 'Yes. The Advocate tracks deadlines and queues the next step along each jurisdiction’s free routes: internal complaint, ombudsman, regulator. Routing to ombudsman schemes, regulated claims professionals and lawyers is built in as a feature, and VF will maintain the escalation-route directory in the open.' },
    { q: 'When does it ship?', a: 'Claims Advocate is in build. The property core comes first: policy decoding, case-file assembly and appeal drafting proven on real denials in the pilot jurisdictions. Motor, travel and health lines follow with deadline automation and ombudsman-format exports, then general availability across initial EU markets and the UK. Real cases shape the pilot.' },
  ],
  related: ['everyday-law-navigator', 'fileit'],
},

// ─── P·14 OFFLINE-FIRST RESPONSE ─────────────────────────────────────
{
  slug: 'offline-first-response',
  name: 'Offline-First Response',
  pn: 'P·14',
  sector: 'EMERGENCY',
  titleTag: 'Coordination, zero bars',
  metaDesc: 'Offline-First Response by VF Empire: emergency coordination on local nodes and device meshes that keeps working when the towers go dark. In build in Malta, EU.',
  ogTitle: 'Disasters take the network down first',
  ogDesc: 'Emergency coordination built offline-first (local mesh, local state, sync when possible) for the hours when the towers are gone. On the VF build slate.',
  appCategory: 'UtilitiesApplication',
  os: 'iOS, Android, Field units',
  ldDesc: 'Offline-First Response is an emergency-coordination system in development by VF Empire Corp Ltd: situation tracking, tasking and messaging designed to operate on local networks and device meshes when wide-area connectivity fails, syncing opportunistically when links return.',
  img: 'p14',
  tagline: 'Built for the hour<br><em class="i">the network dies.</em>',
  sub: 'Europe’s recent disasters share one pattern: the communications infrastructure failed exactly when coordination mattered most. Offline-First Response inverts the assumption: a coordination system that treats the network as a bonus it can run without.',
  chips: ['WORKS DISCONNECTED', 'LOCAL MESH', 'CIVILIAN-ADMINISTRATION GRADE'],
  heroAlt: 'Minimal 3D render of a beacon tower emitting blue pulse rings (Offline-First Response by VF Empire)',
  whyH: 'Every recent disaster<br><span class="mute">wrote the same lesson.</span>',
  whyLead: 'Ahr valley, Valencia and the Iberian blackout were different catastrophes with one repeated failure class: the systems meant to coordinate response assumed connectivity that the catastrophe itself removed.',
  fails: [
    { h: 'Ahr 2021: the network drowned', p: 'The flood destroyed dozens of switching centres and took mobile coverage with it; alerts reached many residents near midnight, hours behind the water. More than 180 people died. Germany introduced cell-broadcast alerting only in 2023, after the event.' },
    { h: 'Valencia 2024: the alert came late', p: 'The ES-Alert message reached phones roughly eight hours after flooding began in parts of the province. 223 people died. The alerting technology existed and worked; activation and coordination failed around it.' },
    { h: 'Iberia 2025: the dependency exposed', p: 'The peninsula-wide blackout took internet traffic down by 80–90%. Operators with battery-backed infrastructure stayed partly up, proof that resilience is an engineering choice, made or not made before the event.' },
    { h: 'Coordination tooling assumes the cloud', p: 'Mainstream incident platforms are cloud services. With the towers dark or the grid down, the coordination layer vanishes at its moment of purpose. Offline capability must be the foundation.' },
  ],
  flowAlt: 'Abstract render of scattered nodes linking into a self-standing blue mesh: coordination without infrastructure',
  cap: 'VALENCIA 2024: THE ALERT ARRIVED ~8 HOURS AFTER THE FLOODING BEGAN. 223 DEAD.',
  whoH: 'For the responders<br><span class="mute">the network abandons.</span>',
  first: {
    icon: 'alert',
    h: 'The municipal crisis team',
    p: 'The first user is the local civil-protection unit, whether the mayor’s crisis cell, the volunteer fire brigade or the parish flood group. They coordinate the first and worst hours, and they are the least equipped tier: no satcom trucks, no federal systems, only phones that stopped working. VF builds the system for them.',
    co: ['FIRST HOURS', 'VOLUNTEER-STAFFED', 'NO SPECIAL KIT', 'LOCAL KNOWLEDGE'],
  },
  aud: [
    { icon: 'shield', h: 'Civil-protection agencies', p: 'Regional and national services get an offline-capable common operating picture that municipal tiers can feed, because it runs on what those tiers have.' },
    { icon: 'users', h: 'Volunteer organisations', p: 'Fire brigades, rescue services and Red Cross chapters get tasking, status and messaging that keeps working in the field, where their work happens.' },
    { icon: 'building', h: 'Critical facilities', p: 'Hospitals, utilities and care homes get a resilient status and request channel to their local coordination cell for the hours the phones are down.' },
    { icon: 'globe', h: 'Communities at known risk', p: 'Flood valleys, fire zones and islands, Malta included, where a locally-owned coordination capability is cheap insurance against a well-documented failure mode.' },
  ],
  howH: 'Coordination that degrades<br><span class="mute">gracefully, starting from zero bars.</span>',
  howLead: 'The design baseline is total wide-area failure. Everything works locally first; connectivity, when present, makes it better rather than making it possible.',
  outs: [
    { h: 'A picture without the cloud', p: 'Incidents, resources, road states and needs tracked on a local node and device mesh. The operating picture lives in the room and the field.' },
    { h: 'Tasking that reaches the field', p: 'Assignments and status flowing over device-to-device links and local radio bridges, hop by hop if that is what the day allows.' },
    { h: 'Sync when the world returns', p: 'The moment any link appears (one bar, one satellite terminal, one restored mast), state reconciles outward automatically. Nothing waits for connectivity; everything uses it.' },
  ],
  mechH: 'Local node, device mesh,<br><span class="mute">opportunistic everything.</span>',
  mechLead: 'The architecture is a hierarchy of survivable layers: hardened local nodes, phone-to-phone meshing, bridges to whatever radio or satellite links exist, with a data model built for disconnection and merge from the first line of code.',
  mechAlt: 'Layered render of a beacon core with concentric blue rings reaching outlying nodes',
  layers: [
    { h: 'The field layer', p: 'Responder phones running the full app offline (capture, tasking, messaging), meshing device-to-device where platform capabilities allow, storing and forwarding where they don’t.' },
    { h: 'The local node', p: 'A battery-backed unit at the coordination point: local Wi-Fi island, state authority, map and data server. The crisis room works because this box works, and this box needs nothing upstream.' },
    { h: 'The bridge layer', p: 'Connectors to what emergency services already trust (digital radio, amateur bridges, satellite terminals), treated as transport of opportunity and never as a dependency.' },
    { h: 'The sync fabric', p: 'A conflict-free data model designed for partition and merge: every node holds usable truth, and any restored link reconciles state without human deduplication.' },
  ],
  roadH: 'Exercised before needed.<br><span class="mute">That is the whole discipline.</span>',
  road: [
    { h: 'The local node', p: 'Core offline coordination: node hardware and software, field app with store-and-forward, the crisis-room picture proven in exercises with a real civil-protection unit.' },
    { h: 'The mesh season', p: 'Device-to-device transports hardened per platform, radio and satellite bridges, multi-node synchronisation across a dispersed incident.' },
    { h: 'The standing capability', p: 'Deployment programmes for municipalities and volunteer organisations, training and exercise packages, and integration with national alerting where interfaces exist.' },
  ],
  paper: { h: 'Assume the network is gone', p: 'The VF position paper on resilient coordination: the failure record from Ahr to the Iberian blackout, and the offline-first architecture it demands.' },
  repo: { h: 'offline-first-response', p: 'Sync fabric and node software. Resilience infrastructure earns trust by being inspectable, so the core protocols will be open.' },
  ctaH: 'The next one is coming.<br><span class="mute">Coordinate anyway.</span>',
  ctaLead: 'Offline-First Response is in build. Civil-protection officers, brigade leads and resilience planners: register interest. Exercise partners shape the system.',
  faq: [
    { q: 'Does it work with no network at all?', a: 'Yes. The design baseline is total wide-area failure. Responder phones run the full app offline (capture, tasking, messaging), a battery-backed local node at the coordination point serves the map and data, and devices mesh phone-to-phone or store and forward. Connectivity, when present, makes it better rather than making it possible.' },
    { q: 'What happens when the network comes back?', a: 'State reconciles outward automatically. The sync fabric uses a conflict-free data model built for partition and merge: every node holds usable truth, and any restored link (one bar, one satellite terminal, one restored mast) reconciles state without human deduplication. Nothing waits for connectivity; everything uses it.' },
    { q: 'Who is it built for?', a: 'The municipal crisis team first: the mayor’s crisis cell, the volunteer fire brigade, the parish flood group. They coordinate the first and worst hours with phones that stopped working. Civil-protection agencies, volunteer organisations, critical facilities such as hospitals and utilities, and communities at known risk, Malta included, follow.' },
    { q: 'Does it need special hardware?', a: 'The field layer runs on responder phones. The local node is a battery-backed unit at the coordination point providing a local Wi-Fi island, state authority and map server, and it needs nothing upstream. Bridges to digital radio, amateur radio and satellite terminals are transport of opportunity, never a dependency.' },
    { q: 'When does it ship?', a: 'Offline-First Response is in build. The local node phase covers node hardware and software, the field app with store-and-forward, and the crisis-room picture proven in exercises with a real civil-protection unit. Hardened device-to-device transports and radio and satellite bridges follow, then deployment and training programmes for municipalities and volunteer organisations.' },
  ],
  related: ['citizen-services-desk', 'nav-it'],
},

// ─── P·16 VF MAIL ────────────────────────────────────────────────────
{
  slug: 'vf-mail',
  name: 'VF Mail',
  pn: 'P·16',
  sector: 'EMAIL',
  titleTag: 'Owned mail system, EU jurisdiction',
  metaDesc: 'VF Mail by VF Empire: a complete email system (server, deliverability shield, address) on metal we hold in EU jurisdiction, carrying our own company mail today.',
  ogTitle: 'Your inbox is someone’s product. Take it back.',
  ogDesc: 'A complete mail system (server, deliverability shield, address) on owned infrastructure. Our own company mail already runs on it. On the VF build slate.',
  appCategory: 'CommunicationApplication',
  os: 'Web, iOS, Android, IMAP/SMTP',
  ldDesc: 'VF Mail is an email system in development by VF Empire Corp Ltd: a complete mail stack (server, security shield and addresses) operated on company-held infrastructure, currently carrying VF Empire’s own corporate mail as its first deployment.',
  img: 'p16',
  tagline: 'Server. Shield. Address.<br><em class="i">All of it yours.</em>',
  sub: 'Email became a duopoly renting you an address inside an advertising ecosystem. VF Mail is the other path: a complete mail system (server, deliverability shield and address) on metal we hold. The first release is downloadable now, free while in Early Access, before the paid launch on November 1.',
  chips: ['FIRST LIGHT: LIVE ON OUR NODE', 'OWN METAL', 'EU JURISDICTION'],
  heroAlt: 'Minimal 3D render of an envelope monolith with a blue wax seal (VF Mail by VF Empire)',
  whyH: 'Two companies read<br><span class="mute">the world’s morning mail.</span>',
  whyLead: 'The most personal document stream in your life (contracts, medical letters, password resets, love and grief) flows through infrastructure owned by a handful of firms whose business model is knowing you. Leaving is technically possible and practically punished.',
  fails: [
    { h: 'The concentration is near-total', p: 'Gmail alone is estimated at around two billion accounts, and industry measurements attribute roughly three-quarters of all email opens to just Apple’s and Google’s mail clients. Email is a protocol; the inbox became an oligopoly.' },
    { h: 'Inside the ad machine', p: 'Google stopped scanning Gmail content for ad targeting in 2017, but the inbox still lives inside an advertising company’s ecosystem, feeding an identity that follows you across the company’s other properties. The mail is the moat.' },
    { h: 'Independence is punished', p: 'Run your own server by the book (SPF, DKIM, DMARC, clean lists) and the big providers may spam-folder you anyway, because your IP has no history with them. The deliverability wall is the lock-in, and it is undocumented by design.' },
    { h: 'Privacy mail proved the demand', p: 'Proton grew past a hundred million accounts on the promise of mail outside the ad economy. The demand is proven; the missing piece is the full-system offer: the whole stack, owned.' },
  ],
  flowAlt: 'Abstract render of mail envelopes flowing through one blue-sealed gateway: the owned mail path',
  cap: 'TWO COMPANIES’ MAIL CLIENTS HANDLE ROUGHLY THREE-QUARTERS OF THE WORLD’S EMAIL OPENS',
  whoH: 'For everyone whose mail<br><span class="mute">should answer to them.</span>',
  first: {
    icon: 'briefcase',
    h: 'Our own companies, already live',
    p: 'VF Mail carries VF Empire’s corporate mail today: the first @vfempire.com inboxes run on our own node, on our own metal. Dogfood first is house law: the system earns the right to carry your mail by carrying ours through the rough edges first.',
    co: ['FIRST LIGHT LIVE', '@VFEMPIRE.COM ON-NODE', 'OUR METAL', 'HOUSE LAW: DOGFOOD FIRST'],
  },
  aud: [
    { icon: 'users', h: 'Individuals leaving the duopoly', p: 'A real address on real infrastructure with EU jurisdiction: your correspondence outside any advertising identity, without becoming your own sysadmin.' },
    { icon: 'building', h: 'Small companies', p: 'Company mail on company terms: custom domain, team inboxes, and a provider whose business model is the service fee.' },
    { icon: 'shield', h: 'Confidentiality professions', p: 'Lawyers, doctors, accountants, journalists: professions whose correspondence carries duties that sit uneasily inside foreign ad-tech ecosystems.' },
    { icon: 'globe', h: 'Sovereignty-minded organisations', p: 'NGOs, associations and public-adjacent bodies that want their mail under European law on inspectable infrastructure.' },
  ],
  howH: 'The whole stack,<br><span class="mute">on metal we hold.</span>',
  howLead: 'Most “private email” is a client on someone else’s cloud. VF Mail is the full system (transport, storage, shield and interface), with the hard part, deliverability, run as a managed discipline so you never fight that war yourself.',
  outs: [
    { h: 'An address that answers to you', p: 'Your mail on infrastructure we hold and you can leave: full export, standard protocols, no hostage data. Ownership means the door opens from the inside.' },
    { h: 'The reputation war, handled', p: 'Warmed IPs, strict authentication, feedback loops, blocklist vigilance: we run the deliverability battle for you as an operations discipline. That is the product’s hardest promise: an operation we run, with no claim of a magic fix.' },
    { h: 'A shield on the front door', p: 'Spam and phishing defence at the server, aggressive transport encryption, and none of the engagement machinery: no ads, no tracking pixels of our own, no profile built from your correspondence.' },
  ],
  mechH: 'Modern stack,<br><span class="mute">old-school ownership.</span>',
  mechLead: 'The build stands on the modern self-hosted mail generation (hardened, memory-safe server software on clean-IP metal), wrapped in the operational layer that makes owned mail practical for people with lives.',
  mechAlt: 'Layered render of a mail server monolith with one blue seal of authentication',
  layers: [
    { h: 'The transport core', p: 'A modern, memory-safe mail server stack (the Stalwart generation of software) on clean-reputation infrastructure in EU jurisdiction, with full standards compliance: SPF, DKIM, DMARC, MTA-STS, DANE.' },
    { h: 'The shield layer', p: 'Inbound filtering, phishing and malware defence, and outbound reputation protection: the security department a mail admin wishes they had, built into the service.' },
    { h: 'The reputation operation', p: 'IP warming, deliverability monitoring, blocklist response and provider-relations discipline, run continuously. Owned mail usually fails at this layer, which is why VF Mail ships as an operated system.' },
    { h: 'The inbox surface', p: 'Clean web and mobile clients plus full IMAP/SMTP for any client you prefer. The interface follows the house style: quiet, fast, and structurally incapable of advertising to you.' },
  ],
  roadH: 'Company mail first.<br><span class="mute">Then yours.</span>',
  road: [
    { h: 'First light: our own mail', p: 'The VF group’s corporate mail live on the owned node: real correspondence, real deliverability battles, the operations playbook written from experience.' },
    { h: 'The hardened node', p: 'Multi-domain hosting, the shield layer completed, client apps polished, migration tooling from the major providers proven on willing pilots.' },
    { h: 'The open door', p: 'General availability for individuals and companies: addresses, custom domains and team mail on VF-held infrastructure: the inbox as a service you own.' },
  ],
  paper: { h: 'The owned inbox', p: 'The VF position paper on mail sovereignty: the deliverability wall, the concentration numbers, and the operations discipline that makes independent mail viable.' },
  repo: { h: 'vf-mail', p: 'Deployment configurations and shield tooling around the open-source mail core. We document what we harden; the independent-mail ecosystem wins together.' },
  ctaH: 'Your mail. Your metal.<br><span class="mute">Our watch.</span>',
  ctaLead: 'VF Mail has first light: our own company mail runs on it now. If you want your inbox back when the doors open, register interest. Early pilots migrate first.',
  faq: [
    { q: 'Is VF Mail available now?', a: 'The first release is downloadable now, free while in Early Access, before the paid launch on November 1. VF Mail already carries VF Empire’s corporate mail: the first @vfempire.com inboxes run on our own node, on our own metal. Early pilots migrate first when the doors open to individuals and companies.' },
    { q: 'What does it cost?', a: 'Free while in Early Access. The paid launch follows on November 1. The provider’s business model is the service fee, with no ads, no tracking pixels of our own and no profile built from your correspondence. Register interest to be among the early pilots who migrate first.' },
    { q: 'Where is my mail hosted?', a: 'On infrastructure VF holds, in EU jurisdiction: a modern, memory-safe mail server stack (the Stalwart generation of software) on clean-reputation metal with full standards compliance: SPF, DKIM, DMARC, MTA-STS, DANE. You can leave at any time: full export, standard protocols, no hostage data. The door opens from the inside.' },
    { q: 'Will my mail land in spam?', a: 'Deliverability is run as a managed operations discipline: warmed IPs, strict authentication, feedback loops, blocklist vigilance and provider-relations work, continuously. Owned mail usually fails at this layer, which is why VF Mail ships as an operated system. It is an operation we run, with no claim of a magic fix.' },
    { q: 'Can I use my own mail client?', a: 'Yes. VF Mail offers clean web and mobile clients plus full IMAP and SMTP for any client you prefer. The interface follows the house style: quiet, fast, and structurally incapable of advertising to you. Small companies get custom domains, team inboxes and a provider whose business model is the service fee.' },
  ],
  related: ['guardian-shield', 'vf-wallet', 'vf-home'],
},

];
