// VF systems pages — content pack B: P·06–P·10.
// Grounded on research pack B (2026-09-11). Honesty law applies: no invented stats, guardrails obeyed.

export default [

// ─── P·06 TRIAGE & CONTINUITY ────────────────────────────────────────
{
  slug: 'triage-continuity',
  name: 'Triage & Continuity',
  pn: 'P·06',
  sector: 'HEALTH',
  titleTag: 'Wellbeing Check-In That Routes to Humans',
  metaDesc: 'Triage & Continuity by VF Empire — on-device wellbeing check-ins that route people to human care and remember the journey. Not another chatbot pretending to be a therapist. In build in Malta, EU.',
  ogTitle: 'Not a therapist. The bridge to one.',
  ogDesc: 'Wellbeing check-ins on your own device, routing to human care, carrying your story so you never repeat it from zero. On the VF build slate.',
  appCategory: 'HealthApplication',
  os: 'iOS, Android',
  ldDesc: 'Triage & Continuity is a wellbeing system in development by VF Empire Corp Ltd: on-device check-ins, structured routing to human mental-health care, and continuity of the care journey with the user’s consent. It is a routing and continuity tool, not a diagnostic or therapeutic device.',
  img: 'p06',
  tagline: 'The bridge to human care,<br><em class="i">not the replacement for it.</em>',
  sub: 'The mental-health system loses people twice: once in the months of waiting, and once in the retelling — every new professional, the same story from zero. Triage & Continuity is a check-in and routing system that keeps you moving toward human care, and carries your journey with you.',
  chips: ['ON-DEVICE FIRST', 'ROUTES TO HUMANS', 'YOU OWN THE RECORD'],
  heroAlt: 'Minimal 3D render of two stepping stones joined by a blue thread — Triage & Continuity by VF Empire',
  whyH: 'The waiting room is months long.<br><span class="mute">And nobody holds your file.</span>',
  whyLead: 'Between the moment someone seeks help and the moment they sit across from a professional lies a gap the system was never built to manage — and a generation of AI chatbots rushed into it with promises they could not keep.',
  fails: [
    { h: 'The wait is the wound', p: 'In Germany, analyses prepared for the Bundestag document typical waits of three to six months for a therapy place. Demand for support keeps climbing across Europe — the front door of the system is where people are lost.' },
    { h: 'The story resets every time', p: 'GP to counsellor to therapist to crisis line — each handover starts from zero, and the retelling itself is a documented burden. Continuity of the journey is the unowned problem in mental-health care.' },
    { h: 'The chatbot era overpromised', p: 'AI “therapist” apps have ended in shutdowns, FTC action over data sharing, and litigation over harms to vulnerable users. The lesson is not that software has no role — it is that pretending software is a clinician is the wrong role.' },
    { h: 'The cost lands everywhere', p: 'Deloitte estimates poor mental health costs UK employers around £51 billion a year. Behind the number is the same mechanism: people struggling in the gap before care, invisibly.' },
  ],
  flowAlt: 'Abstract render of a path of stones crossing toward a lit doorway — the route to human care',
  cap: 'GERMANY: 3–6 MONTH TYPICAL WAITS FOR A THERAPY PLACE',
  whoH: 'For the person<br><span class="mute">in the gap.</span>',
  first: {
    icon: 'heart',
    h: 'The person waiting for care',
    p: 'The system’s first user is the person who has already asked for help and been handed a waiting time. Structured check-ins hold the thread, the record grows instead of resetting, and if things worsen, routing escalates — to humans, every time.',
    co: ['ALREADY SEEKING HELP', 'MONTHS FROM A PLACE', 'JOURNEY HELD', 'HUMAN ESCALATION'],
  },
  aud: [
    { icon: 'users', h: 'Families & supporters', p: 'The people carrying someone through the wait get guidance on what to watch for and where the real doors are — without ever seeing more than the person chooses to share.' },
    { icon: 'briefcase', h: 'Employers of care', p: 'Organisations that want to offer staff something honest: a private check-in and routing tool, structurally incapable of reporting anyone’s inner life to their employer.' },
    { icon: 'heart', h: 'Practitioners, on consent', p: 'When the user chooses, a professional receives an arrival summary instead of a cold start — the journey so far, in minutes, not the first three sessions.' },
    { icon: 'globe', h: 'Underserved regions', p: 'Places where the nearest practitioner is a ferry or a hundred kilometres away. Routing knows the real map of available care, including remote options.' },
  ],
  howH: 'Held, routed,<br><span class="mute">and never asked to start over.</span>',
  howLead: 'Triage & Continuity does three honest things: it checks in, it routes to human care, and it remembers — with the user owning every word of the record. It does not diagnose, does not treat, and does not pretend.',
  outs: [
    { h: 'A thread that holds', p: 'Structured check-ins across the waiting months — a felt trajectory made visible, so neither the person nor their eventual practitioner starts blind.' },
    { h: 'The right door, faster', p: 'Routing built on the actual care landscape — GPs, therapists, community services, crisis lines — matched to need, location and urgency, with escalation paths that go straight to humans.' },
    { h: 'Your story, portable', p: 'The journey record belongs to the user, on their device — shared with a chosen professional in one consented handover, never sold, never mined.' },
  ],
  mechH: 'On the device.<br><span class="mute">Off the market.</span>',
  mechLead: 'Data about a person’s inner life is the most sensitive class there is. The architecture answers accordingly: processing on the user’s own device, a record only the user holds, and routing logic that treats escalation to humans as the primary function — not a liability footnote.',
  mechAlt: 'Layered render of a private device core with one blue continuity thread rising from it',
  layers: [
    { h: 'The check-in layer', p: 'Brief structured conversations and validated-questionnaire-style self-reports, processed on-device. Designed for consistency over the long haul, not engagement metrics.' },
    { h: 'The continuity record', p: 'A longitudinal journal of check-ins, encrypted on the user’s device. The user reads it, exports it, deletes it. There is no server-side behavioural profile — by architecture.' },
    { h: 'The routing engine', p: 'A maintained directory of real care pathways per region, with urgency-aware matching and hard-coded crisis escalation to human services. This layer is the product’s conscience.' },
    { h: 'The handover surface', p: 'Consented, structured summaries for the professional the user reaches — the journey so far, in clinical-friendly form, generated only when the user says so.' },
  ],
  roadH: 'Built with clinicians,<br><span class="mute">not instead of them.</span>',
  road: [
    { h: 'The check-in core', p: 'On-device check-in and continuity record, crisis escalation paths wired and tested, routing directory live for the pilot regions.' },
    { h: 'The clinical loop', p: 'Practitioner handover format developed with working clinicians; routing coverage expanded; regulatory review of every claim the product makes.' },
    { h: 'The open bridge', p: 'General availability in initial EU markets, integrations with public referral systems where they exist, and multilingual delivery.' },
  ],
  paper: { h: 'What software should not pretend to be', p: 'The VF position paper on mental-health AI: the case for routing-and-continuity over simulated therapy, and the regulatory line the product is built behind.' },
  repo: { h: 'triage-continuity', p: 'On-device record format and routing framework. The crisis-escalation logic will be publicly documented — that layer should never be a trade secret.' },
  ctaH: 'Software that knows<br><span class="mute">what it is not.</span>',
  ctaLead: 'Triage & Continuity is in build, with clinical review baked into the roadmap. If you have lived the gap — or work in it — register interest. This one is built carefully.',
},

// ─── P·07 SITE TRUTH ENGINE ──────────────────────────────────────────
{
  slug: 'site-truth-engine',
  name: 'Site Truth Engine',
  pn: 'P·07',
  sector: 'CONSTRUCTION',
  titleTag: 'Progress Truth From Cameras Already On Site',
  metaDesc: 'Site Truth Engine by VF Empire — construction progress verified against plans, risk-condition flagging and materials flow, read from the cameras already on site. In build in Malta, EU.',
  ogTitle: 'The site already films itself. Nobody was watching.',
  ogDesc: 'Progress verification, risk-condition flagging and materials tracking from existing site cameras — no new hardware estate. On the VF build slate.',
  appCategory: 'BusinessApplication',
  os: 'Web, iOS, Android',
  ldDesc: 'Site Truth Engine is a construction-intelligence system in development by VF Empire Corp Ltd: progress verification against plans, flagging of risk conditions for human review, and materials-flow tracking, computed from camera infrastructure already installed on site.',
  img: 'p07',
  tagline: 'The site says what happened.<br><em class="i">Every day. In writing.</em>',
  sub: 'Construction runs on claimed progress — and settles its disputes over what actually happened months later, at legal rates. Site Truth Engine reads the cameras a site already has and produces the daily record: what advanced, what stalled, what looks unsafe, what arrived.',
  chips: ['EXISTING CAMERAS', 'PLAN-VERIFIED PROGRESS', 'HUMAN-REVIEWED FLAGS'],
  heroAlt: 'Minimal 3D render of a crane lifting an ordered stack of blocks — Site Truth Engine by VF Empire',
  whyH: 'An industry that builds everything<br><span class="mute">and can’t prove what it did yesterday.</span>',
  whyLead: 'Construction’s productivity, rework and dispute problems share one root: the absence of a trusted, continuous record of what actually happened on site. The evidence infrastructure already exists — it is bolted to the scaffolding, recording nobody-watches footage.',
  fails: [
    { h: 'Productivity flatlined', p: 'McKinsey’s landmark analysis put construction productivity growth at roughly 1% a year over two decades — trailing nearly every other industry. You cannot improve a process you cannot see.' },
    { h: 'Rework eats the margin', p: 'Industry studies place direct rework at around 5% of project cost, with broader estimates running to 10–25% once knock-on effects count. Much of it traces to work proceeding on top of unverified prior work.' },
    { h: 'The site is the danger zone', p: 'Eurostat attributes roughly a quarter of all fatal workplace accidents in the EU to construction — the deadliest major sector. Risk conditions are visible in footage long before they are visible in reports.' },
    { h: 'Disputes settle on bad memory', p: 'Arcadis has reported average construction-dispute values in the tens of millions of dollars, fought largely over what happened when. A continuous visual record changes the entire economics of the argument.' },
  ],
  flowAlt: 'Abstract render of camera sightlines converging onto a rising block structure — the site observed',
  cap: 'EUROSTAT: ≈1 IN 4 FATAL EU WORKPLACE ACCIDENTS HAPPEN IN CONSTRUCTION',
  whoH: 'For everyone whose money<br><span class="mute">or name is on the build.</span>',
  first: {
    icon: 'building',
    h: 'The small and mid-size contractor',
    p: 'The enterprise site-intelligence players sell to megaprojects. Site Truth Engine starts with the contractor running three to ten sites on cameras they already bought — the operator who needs the truth layer most and was priced out of it first.',
    co: ['EXISTING CCTV', 'MULTIPLE SMALL SITES', 'NO BIM TEAM', 'PRICED FOR SMEs'],
  },
  aud: [
    { icon: 'eye', h: 'Site & project managers', p: 'The morning site-state briefing generated overnight: progress against plan, flagged conditions for human review, deliveries logged. The walk-around becomes verification, not discovery.' },
    { icon: 'briefcase', h: 'Developers & owners', p: 'Independent progress truth on the asset being paid for — drawdown decisions and contractor conversations grounded in the record, not the claim.' },
    { icon: 'shield', h: 'Safety officers', p: 'Risk conditions — blocked routes, missing edge protection, unsafe storage — flagged for qualified human review. The system watches the work and the site, never rates the workers.' },
    { icon: 'truck', h: 'Quantity surveyors & insurers', p: 'Valuations, claims and premiums built on continuous visual evidence — the daily record that today exists only as contested recollection.' },
  ],
  howH: 'From dead footage<br><span class="mute">to a living record.</span>',
  howLead: 'The wedge is deliberate: no new hardware estate, no BIM prerequisite, no six-month integration. Point the engine at the cameras the site already has, load the plans, and the record starts tonight.',
  outs: [
    { h: 'Progress, verified', p: 'Work-in-place detected and matched against the programme — claimed percent-complete replaced by observed percent-complete, dated and archived.' },
    { h: 'Risk seen early', p: 'Hazardous conditions surfaced from the footage and queued for the safety officer’s judgement — a second set of eyes that never gets tired, never a verdict.' },
    { h: 'The dispute-proof diary', p: 'A timestamped visual site diary that accumulates by itself — the evidence layer for delay claims, valuations and handover, built as a by-product of just running.' },
  ],
  mechH: 'Cameras in.<br><span class="mute">Accountability out.</span>',
  mechLead: 'The engine treats the site’s existing CCTV as a sensor array, runs vision models against plans and programme, and publishes everything into one reviewable record — with worker privacy engineered in, not appended.',
  mechAlt: 'Layered render of stacked construction planes scanned by one blue sightline',
  layers: [
    { h: 'The intake layer', p: 'Connects to existing site cameras — fixed CCTV, time-lapse units, periodic capture — normalising whatever the site already runs. New hardware is an option, never the ticket price.' },
    { h: 'The vision core', p: 'Detection models for structural elements, plant, materials and site conditions, tuned per project phase. Trained to watch work and environment — faces are irrelevant to it and treated accordingly.' },
    { h: 'The truth ledger', p: 'Observations reconciled against drawings and programme into an append-only site record: progress states, flagged conditions, delivery events — every entry dated, sourced, and exportable as evidence.' },
    { h: 'The review surface', p: 'Dashboards and morning briefs for managers; a flag queue for safety review; owner views scoped to their asset. Humans confirm; the engine never acts alone.' },
  ],
  roadH: 'One site watched,<br><span class="mute">then the industry’s memory.</span>',
  road: [
    { h: 'The first site', p: 'Live pilot on working sites: camera intake, progress detection against plans, the daily brief and site diary proven with real contractors.' },
    { h: 'The flag season', p: 'Risk-condition flagging with safety-officer review loops, materials and delivery tracking, multi-site portfolio views.' },
    { h: 'The evidence standard', p: 'General availability, QS and insurance export formats, and programme-integration partnerships — the site record as a standard project deliverable.' },
  ],
  paper: { h: 'The observable site', p: 'The VF position paper on construction truth infrastructure: why the record must be continuous, how worker privacy is engineered, and what the dispute economics become.' },
  repo: { h: 'site-truth-engine', p: 'Intake adapters and ledger format. The camera-normalisation layer will be opened — every site intelligence tool should read every camera.' },
  ctaH: 'Stop arguing about<br><span class="mute">what happened. Know.</span>',
  ctaLead: 'Site Truth Engine is in build. If you run sites on cameras nobody watches, register interest — pilot sites get the truth layer first.',
},

// ─── P·08 GRID & HOME OPTIMISER ──────────────────────────────────────
{
  slug: 'grid-home-optimiser',
  name: 'Grid & Home Optimiser',
  pn: 'P·08',
  sector: 'ENERGY',
  titleTag: 'Local Energy Intelligence for Solar Homes',
  metaDesc: 'Grid & Home Optimiser by VF Empire — local agents balancing solar, storage and consumption in the home, grid-aware by design. Runs on your hardware, not a vendor cloud. In build in Malta, EU.',
  ogTitle: 'Your roof makes power. Your house wastes it.',
  ogDesc: 'A local energy brain balancing solar, battery and consumption against real prices and real weather — owned by the household. On the VF build slate.',
  appCategory: 'UtilitiesApplication',
  os: 'Home hub, iOS, Android, Web',
  ldDesc: 'Grid & Home Optimiser is an energy-management system in development by VF Empire Corp Ltd: local optimisation agents that coordinate solar generation, battery storage and household consumption, running on hardware in the home with grid-aware scheduling.',
  img: 'p08',
  tagline: 'Every roof a power plant.<br><em class="i">Every home its own operator.</em>',
  sub: 'Europe put panels on millions of roofs and then left the households to guess. Most self-generated power is used badly or exported cheap while the same house buys peak electricity at night. Grid & Home Optimiser is the missing operator — a local brain that runs the house like a tiny utility.',
  chips: ['RUNS LOCAL', 'PRICE & WEATHER AWARE', 'VENDOR-NEUTRAL'],
  heroAlt: 'Minimal 3D render of a house with solar roof and a single blue energy dot — Grid & Home Optimiser by VF Empire',
  whyH: 'The hardware revolution happened.<br><span class="mute">The intelligence never arrived.</span>',
  whyLead: 'Solar, batteries, heat pumps, EVs — the equipment is on the wall and in the driveway. What is missing in the ordinary household is coordination: the layer that decides, hour by hour, what should run, charge, store or sell.',
  fails: [
    { h: 'Self-consumption runs low', p: 'Unmanaged solar homes typically use only around 20–40% of what their own roof generates; with storage and smart scheduling, studies show that share can rise dramatically. The gap between those numbers is pure coordination — currently done by nobody.' },
    { h: 'The grid pays for the chaos', p: 'Germany spent roughly €2.8 billion on grid stabilisation measures in 2024, with over a terawatt-hour of solar curtailed. Millions of uncoordinated homes are part of the problem; coordinated, they are part of the answer.' },
    { h: 'Dynamic pricing is invisible', p: 'Surveys find more than half of German households have never even heard of dynamic electricity tariffs. The price signal exists; without an agent watching it, it might as well not.' },
    { h: 'Every vendor built a silo', p: 'Inverter app, battery app, wallbox app, heat-pump app — none of them talking. Five million German PV systems and a million balcony plants, each an island of good hardware and absent orchestration.' },
  ],
  flowAlt: 'Abstract render of sun, battery and house forms linked by one blue circuit — the home energy loop closed',
  cap: 'GERMANY 2024: ≈€2.8BN GRID STABILISATION, >1 TWH OF SOLAR CURTAILED',
  whoH: 'For the household<br><span class="mute">that already invested.</span>',
  first: {
    icon: 'home',
    h: 'The solar household',
    p: 'The first user already made the leap: panels up, maybe a battery, maybe a wallbox — and a nagging sense the system underdelivers. The Optimiser is the intelligence purchase that makes the hardware purchases finish paying off.',
    co: ['PV ON THE ROOF', 'MIXED-VENDOR KIT', 'TIME-OF-USE READY', 'OWNS THE DATA'],
  },
  aud: [
    { icon: 'bolt', h: 'Battery & EV owners', p: 'Charge from sun, discharge at peak, fill the car on the cheapest hours — the arbitrage every storage owner intends to do and no one does by hand.' },
    { icon: 'leaf', h: 'Heat-pump homes', p: 'Heating is the biggest load in the house and the most shiftable. Thermal scheduling against forecast and price, with comfort as a hard constraint, not a casualty.' },
    { icon: 'users', h: 'Balcony-plant beginners', p: 'The million-strong Balkonkraftwerk wave — small systems whose owners deserve the same intelligence, scaled down to a plug-in reality.' },
    { icon: 'building', h: 'Small commercial roofs', p: 'Workshops, farms and shops with PV on the shed: the same optimisation with load profiles that work business hours.' },
  ],
  howH: 'The house decides hourly.<br><span class="mute">You just live in it.</span>',
  howLead: 'The Optimiser watches forecasted sun, tariff windows and household patterns, and schedules the controllable loads — locally, continuously, without asking the household to become energy traders.',
  outs: [
    { h: 'Own power, used', p: 'Self-consumption pushed toward what the hardware can actually deliver — the roof’s output routed into the house’s real needs instead of exported for cents.' },
    { h: 'Peak prices, avoided', p: 'Shiftable loads — water, heat, EV, battery — moved into cheap and sunny windows automatically, with tariff awareness the household never has to think about.' },
    { h: 'Grid-friendly by design', p: 'A coordinated home smooths its own peaks — easier on the local grid and ready for the flexible-consumption frameworks Europe is rolling out.' },
  ],
  mechH: 'Local brain.<br><span class="mute">Open connectors. Your metal.</span>',
  mechLead: 'The architecture is the VF standard: intelligence running on a hub in the house, vendor-neutral connectors to whatever equipment is installed, and a household that owns every byte of its own energy life.',
  mechAlt: 'Layered render of an energy hub with radiating blue connections to solar, battery and loads',
  layers: [
    { h: 'The device layer', p: 'Vendor-neutral connectors to inverters, batteries, wallboxes, heat pumps and meters over open protocols wherever they exist. Mixed-vendor homes are the design case, not the edge case.' },
    { h: 'The forecast core', p: 'Solar yield from weather models and the roof’s own history, consumption patterns learned per household, tariff calendars ingested per supplier.' },
    { h: 'The scheduling engine', p: 'Rolling optimisation that plans the next hours — charge, hold, run, defer — re-solved as forecasts shift. Comfort and user overrides are hard constraints; savings never come out of warm showers.' },
    { h: 'The household surface', p: 'One app for the whole energy life: live flows, the plan, the receipts of what the coordination achieved — replacing five vendor silo apps with one owned view.' },
  ],
  roadH: 'One meter cabinet<br><span class="mute">at a time.</span>',
  road: [
    { h: 'The first homes', p: 'Hub software on pilot households: device connectors for common EU equipment, solar and load forecasting, first closed-loop scheduling of battery and major loads.' },
    { h: 'The tariff season', p: 'Dynamic-tariff integration across suppliers, heat-pump thermal scheduling, EV-charging orchestration, balcony-plant mode.' },
    { h: 'The neighbourhood view', p: 'General availability, installer partnerships, and grid-flexibility readiness as EU demand-response frameworks open to households.' },
  ],
  paper: { h: 'The uncoordinated megawatt', p: 'The VF position paper on household energy intelligence: the coordination gap in Europe’s rooftop fleet and the case for local-first architecture.' },
  repo: { h: 'grid-home-optimiser', p: 'Connector framework and scheduling core. Device connectors will be open — no household should be locked out because of its inverter brand.' },
  ctaH: 'You bought the power plant.<br><span class="mute">Hire the operator.</span>',
  ctaLead: 'Grid & Home Optimiser is in build. If your roof generates and your apps don’t talk, register interest — pilot homes define the connector priority list.',
},

// ─── P·09 SELF-TRAINING QC VISION ────────────────────────────────────
{
  slug: 'self-training-qc-vision',
  name: 'Self-Training QC Vision',
  pn: 'P·09',
  sector: 'MANUFACTURING',
  titleTag: 'Defect Detection a Floor Manager Can Teach',
  metaDesc: 'Self-Training QC Vision by VF Empire — visual defect detection a floor manager teaches in an afternoon. No ML engineers, no six-month integration. In build in Malta, EU.',
  ogTitle: 'Quality control that learns from the person who knows',
  ogDesc: 'Camera-based defect detection taught by your own quality people in an afternoon — assistive, human-confirmed, priced for SME factories. On the VF build slate.',
  appCategory: 'BusinessApplication',
  os: 'Edge unit, Web',
  ldDesc: 'Self-Training QC Vision is a manufacturing quality system in development by VF Empire Corp Ltd: camera-based defect detection that production and quality staff train themselves by example, running on edge hardware at the line with human confirmation of every disposition.',
  img: 'p09',
  tagline: 'Your best inspector’s eye,<br><em class="i">on every part, every shift.</em>',
  sub: 'Machine vision for quality control exists — behind ML consultants, integration projects and enterprise pricing. Self-Training QC Vision moves the teaching to the person who actually knows what a defect looks like: your quality lead, showing the system examples, an afternoon at a time.',
  chips: ['TAUGHT BY YOUR PEOPLE', 'EDGE-RUN AT THE LINE', 'HUMAN CONFIRMS'],
  heroAlt: 'Minimal 3D render of conveyor cubes with one blue-scanned unit — Self-Training QC Vision by VF Empire',
  whyH: 'The cost of bad quality is enormous.<br><span class="mute">The tools to catch it went enterprise.</span>',
  whyLead: 'Quality escapes are one of manufacturing’s largest quiet costs, and small factories carry them with the fewest defences — because the AI inspection industry was built around customers with ML teams.',
  fails: [
    { h: 'Quality costs real margin', p: 'Industry estimates associated with ASQ place the cost of poor quality at 15–20% of sales for many manufacturers — scrap, rework, returns and the customers who quietly never come back.' },
    { h: 'The adoption cliff', p: 'Eurostat data shows around 30% of large EU enterprises using AI against roughly 7% of small ones. In quality inspection, that gap maps directly to who ships defects and who catches them.' },
    { h: 'Projects, not products', p: 'Conventional vision systems arrive as integration projects: consultants, custom training, months of tuning per part variant. By some industry estimates most AI projects never reach production at all — a risk small firms cannot underwrite.' },
    { h: 'The knowledge is already in the room', p: 'Every factory has the person who can spot the bad part at a glance. That expertise currently leaves with retirement and shift changes. It should be teachable to a camera — by that person, directly.' },
  ],
  flowAlt: 'Abstract render of parts streaming through a blue inspection gate — the line watched piece by piece',
  cap: 'EUROSTAT: ≈30% OF LARGE EU FIRMS USE AI — ≈7% OF SMALL ONES',
  whoH: 'For the factory<br><span class="mute">without an AI department.</span>',
  first: {
    icon: 'eye',
    h: 'The SME production line',
    p: 'The design customer runs one to five lines, employs no data scientist, and lives or dies on reputation with a handful of key buyers. The system must earn its place with that operation: taught in an afternoon, useful in a week, priced like equipment — not like a consulting engagement.',
    co: ['NO ML TEAM', '1–5 LINES', 'REPUTATION-CRITICAL', 'EQUIPMENT-PRICED'],
  },
  aud: [
    { icon: 'users', h: 'Quality leads', p: 'The person who knows what wrong looks like becomes the teacher: label examples on a screen, correct the system’s calls, watch it converge on their eye.' },
    { icon: 'building', h: 'Plant managers', p: 'Defect trends per line, shift and variant — the quality picture as a live dashboard instead of a monthly complaint-driven surprise.' },
    { icon: 'briefcase', h: 'Contract manufacturers', p: 'Documented inspection on every unit as a sales asset — proof of process for the buyers who audit before they order.' },
    { icon: 'layers', h: 'High-mix producers', p: 'Short runs and frequent changeovers, where classic vision tuning never pays off — teaching a new variant must take minutes, not a consulting visit.' },
  ],
  howH: 'Show it examples.<br><span class="mute">Confirm its calls. That’s the method.</span>',
  howLead: 'The system is assistive by design: it flags, a human disposes. Every confirmation is also training data, so the detector sharpens as a side effect of the line simply running.',
  outs: [
    { h: 'Escapes caught at the line', p: 'Every unit inspected at production speed, suspects flagged for human decision before they reach a box, a truck, or a customer.' },
    { h: 'Teaching, not integrating', p: 'New part, new defect class, new variant — taught by example from the floor, in-session. The six-month vision project collapses into an afternoon.' },
    { h: 'Quality memory built', p: 'Every flagged unit archived with image and disposition: the factory’s defect history becomes searchable evidence for audits, claims and process fixes.' },
  ],
  mechH: 'Edge box at the line.<br><span class="mute">Learning loop on the floor.</span>',
  mechLead: 'Cameras over the line, an edge unit beside it, a teaching screen in the quality office — and a training loop that lives entirely inside the factory. Product images never need to leave the building.',
  mechAlt: 'Layered render of an edge unit scanning a stream of parts under one blue beam',
  layers: [
    { h: 'The capture layer', p: 'Industrial cameras positioned over the line, triggered per unit or continuously — commodity hardware where possible, matched to line speed and part size.' },
    { h: 'The edge core', p: 'Detection models running on an on-site unit at line speed. On-premise by default: the factory’s parts, defects and volumes stay the factory’s business.' },
    { h: 'The teaching loop', p: 'Example-based training driven by quality staff: label, correct, confirm. Few-shot techniques mean useful detection from dozens of examples, converging with every shift worked.' },
    { h: 'The quality surface', p: 'The flag queue for dispositions, trend dashboards per line and variant, and the archived defect record — exportable for audits and customer quality agreements.' },
  ],
  roadH: 'One line proven,<br><span class="mute">then every floor like it.</span>',
  road: [
    { h: 'The first line', p: 'Pilot deployments on real SME lines: capture setup, edge detection, the teaching loop proven with working quality leads on their actual defect classes.' },
    { h: 'The variant season', p: 'High-mix fast-teaching workflows, multi-line and multi-site views, audit-grade record exports.' },
    { h: 'The floor standard', p: 'General availability with equipment-style pricing, integrator partnerships, and connectors into the MES and ERP systems factories already run.' },
  ],
  paper: { h: 'Vision without the priesthood', p: 'The VF position paper on SME machine vision: why teaching beat integrating, and what assistive-only architecture means for accountability on the line.' },
  repo: { h: 'qc-vision', p: 'Edge runtime and teaching-loop tooling. Camera and line-integration adapters will be opened for the integrator ecosystem.' },
  ctaH: 'Your quality lead already knows.<br><span class="mute">Let them teach the machine.</span>',
  ctaLead: 'Self-Training QC Vision is in build. If your factory ships on reputation and inspects on tired eyes, register interest — pilot lines are chosen from this list.',
},

// ─── P·10 DIFFERENT-MINDS ENGINE ─────────────────────────────────────
{
  slug: 'different-minds-engine',
  name: 'Different-Minds Engine',
  pn: 'P·10',
  sector: 'EDUCATION',
  titleTag: 'Learning Built for Neurodivergent Students First',
  metaDesc: 'Different-Minds Engine by VF Empire — adaptive learning designed first for dyslexic, ADHD and autistic students, the learners mainstream edtech treats as edge cases. In build in Malta, EU.',
  ogTitle: 'Built for the minds the mainstream calls edge cases',
  ogDesc: 'Adaptive learning designed neurodivergent-first — dyslexia, ADHD, autism — with families and educators in the loop. On the VF build slate.',
  appCategory: 'EducationalApplication',
  os: 'iOS, Android, Web',
  ldDesc: 'Different-Minds Engine is an educational system in development by VF Empire Corp Ltd: adaptive learning experiences designed first for dyslexic, ADHD and autistic students, with educator and family involvement and children’s-privacy-first architecture. It is a learning tool; it does not diagnose or screen.',
  img: 'p10',
  tagline: 'Not remedial. Not an afterthought.<br><em class="i">Designed for how they think.</em>',
  sub: 'Roughly one child in ten shows signs of dyslexia by common estimates; ADHD and autism add millions more. Mainstream edtech serves them with settings menus bolted onto neurotypical products. Different-Minds Engine inverts the order: designed for these learners first, and better for everyone because of it.',
  chips: ['NEURODIVERGENT-FIRST', 'FAMILY & EDUCATOR LOOP', 'CHILD-PRIVACY BY DESIGN'],
  heroAlt: 'Minimal 3D render of toy building blocks with one uniquely shaped blue block — Different-Minds Engine by VF Empire',
  whyH: 'Millions of learners.<br><span class="mute">One settings toggle each.</span>',
  whyLead: 'The population is enormous, the support systems are buckling, and the technology response so far has been accessibility checkboxes on products designed for someone else’s attention span.',
  fails: [
    { h: 'This is not an edge case', p: 'Estimates commonly place dyslexia around one in ten people, ADHD near one in twenty children, autism at one in a hundred or more. Every classroom in Europe contains these minds — “edge case” was always a design excuse.' },
    { h: 'The support system is over capacity', p: 'In England, under half of education-and-care plans were issued within the statutory 20-week deadline in recent data, with thousands of families waiting over a year. Whatever a child needs, the queue arrives first.' },
    { h: 'Retrofitted, not designed', p: 'Mainstream platforms add dyslexia fonts and call it inclusion. Pacing, working-memory load, sensory environment, interest-driven motivation — the actual design variables for these learners — go untouched.' },
    { h: 'The cost compounds for life', p: 'Only around three in ten autistic adults are in work against roughly eight in ten non-disabled adults. Educational experiences that fail these minds early compound into lifelong exclusion — the stakes are not academic.' },
  ],
  flowAlt: 'Abstract render of varied block shapes each finding a matching slot along a blue path — many minds, many routes',
  cap: 'ENGLAND: THOUSANDS OF FAMILIES WAITED OVER A YEAR FOR STATUTORY SUPPORT PLANS',
  whoH: 'For the learners —<br><span class="mute">and everyone holding their ladder.</span>',
  first: {
    icon: 'book',
    h: 'The student the classroom loses',
    p: 'The bright child drowning in text, the racing mind that cannot hold a worksheet, the deep-focus learner the timetable interrupts. The Engine is built around their cognitive reality — adjusting presentation, pacing and structure to the mind in front of it, never asking the mind to apologise first.',
    co: ['DYSLEXIC READERS', 'ADHD ATTENTION', 'AUTISTIC FOCUS', 'STRENGTHS-FIRST'],
  },
  aud: [
    { icon: 'users', h: 'Parents', p: 'The family carrying the waiting lists gets a tool that works tonight — visibility into how their child actually learns, and materials shaped to it, at home.' },
    { icon: 'book', h: 'Teachers & SENCOs', p: 'Support staff stretched across growing caseloads get per-learner insight and ready-adapted materials — capacity, not another platform to administer.' },
    { icon: 'heart', h: 'Learning therapists', p: 'Specialists get a between-sessions instrument: practice tuned to their programme, progress made visible across the week they don’t see.' },
    { icon: 'building', h: 'Schools & authorities', p: 'Institutions get neurodivergent-first provision that is deployable now — with children’s-data protections engineered to the strictest reading of EU rules.' },
  ],
  howH: 'The material bends.<br><span class="mute">The learner doesn’t have to.</span>',
  howLead: 'The Engine is a learning tool with a hard boundary: it adapts and teaches, it does not diagnose or screen. What it changes is the daily experience — content meeting the mind where it is, in the mode it thinks in.',
  outs: [
    { h: 'Presentation that fits', p: 'Text load, structure, sensory intensity and modality adjusted per learner — reading-heavy material becoming visual, sequential, spoken or interactive as the mind requires.' },
    { h: 'Pacing that respects attention', p: 'Session shapes built for real attention patterns — short arcs, movement breaks, hyperfocus runs — treating the learner’s rhythm as a parameter, not a failure.' },
    { h: 'Progress made visible', p: 'Growth shown against the learner’s own baseline, shared with the adults the family chooses — evidence of a mind moving, for children who rarely get to see themselves win.' },
  ],
  mechH: 'A profile, a pedagogy,<br><span class="mute">and a hard privacy floor.</span>',
  mechLead: 'Underneath is a learner model built with specialist input, a content engine that renders one curriculum many ways — and a children’s-data architecture designed to the strictest reading of the rules, because the users are children.',
  mechAlt: 'Layered render of one learning core rendering into multiple differently shaped blue outputs',
  layers: [
    { h: 'The learner profile', p: 'A model of how this student learns — modality, pacing, load tolerance, interests — built from observed interaction and educator input. A learning profile, never a diagnostic instrument.' },
    { h: 'The adaptation engine', p: 'One curriculum, many renderings: the same concept expressed across modalities and structures, selected and sequenced against the profile in real time.' },
    { h: 'The evidence loop', p: 'Progress measured against the learner’s own history, feeding both the adaptation and the human reports — with educators and specialists shaping what is measured at all.' },
    { h: 'The guardian layer', p: 'Children’s-privacy architecture: data minimisation, parental control, no advertising, no profiling beyond the learning purpose, EU hosting. The floor, not the marketing.' },
  ],
  roadH: 'Built with specialists,<br><span class="mute">proven with families.</span>',
  road: [
    { h: 'The reading core', p: 'First vertical: literacy for dyslexic learners, co-designed with specialist educators, piloted with families — profile, adaptation and evidence loop proven end to end.' },
    { h: 'The attention build', p: 'ADHD-first pacing architecture and autistic-first structure and sensory controls, numeracy coverage, educator dashboards.' },
    { h: 'The open classroom', p: 'General availability for families, school and authority licensing, multilingual delivery — Maltese included, in-house.' },
  ],
  paper: { h: 'Edge case is a design decision', p: 'The VF position paper on neurodivergent-first education: why designing for these minds first produces better tools for all minds, and the evidence bar the product holds itself to.' },
  repo: { h: 'different-minds-engine', p: 'Adaptation framework and content-rendering pipeline. The learner-profile schema will be published for specialist and academic scrutiny.' },
  ctaH: 'Different minds were never<br><span class="mute">the edge case. Build like it.</span>',
  ctaLead: 'Different-Minds Engine is in build, specialists in the loop from day one. If you parent, teach or support one of these minds, register interest — pilot families shape everything.',
},

];
