// VF systems pages: content pack A: P·01–P·05.
// Grounded on research pack A (2026-09-11). Honesty law applies: no invented stats, guardrails obeyed.

export default [

// ─── P·01 FIELD INTELLIGENCE ─────────────────────────────────────────
{
  slug: 'field-intelligence',
  name: 'Field Intelligence',
  pn: 'P·01',
  sector: 'AGRICULTURE',
  titleTag: 'Crop AI for family farms',
  metaDesc: 'Field Intelligence by VF Empire: crop health, irrigation and yield intelligence for small and family farms, from free satellite data. In build in Malta, EU.',
  ogTitle: 'crop intelligence for the farms the industry skips',
  ogDesc: 'Agronomist-grade crop health, irrigation and yield AI scaled down to the family farm. On the VF build slate.',
  appCategory: 'BusinessApplication',
  os: 'Web, iOS, Android',
  ldDesc: 'Field Intelligence is an agricultural AI system in development by VF Empire Corp Ltd: crop health monitoring, irrigation guidance and yield intelligence designed for small and family farms, starting from satellite and weather data the farm already has access to.',
  img: 'p01',
  tagline: 'The agronomist <em class="i">every</em> farm can afford to consult.',
  sub: 'The precision-agriculture industry built its tools for estates measured in thousands of hectares. Field Intelligence takes the same class of crop-health, irrigation and yield analysis and scales it down to the small farms that feed Europe.',
  chips: ['SATELLITE + WEATHER DATA', 'SMALL-FARM FIRST', 'EU GROWN'],
  heroAlt: 'Minimal 3D render of a ploughed field with a single blue sprout: Field Intelligence by VF Empire',
  whyH: 'Precision farming exists.<br><span class="mute">Small farms were priced out of it.</span>',
  whyLead: 'The technology gap in agriculture is about who gets access. The numbers are stark: the larger the farm, the more likely it already runs on data. The smaller the farm, the more likely it runs on memory and hope.',
  fails: [
    { h: 'Adoption follows farm size', p: 'US Department of Agriculture data shows around 73% of large crop farms use guidance and precision systems, against roughly 10% of small ones. Yield-mapping adoption shows the same cliff: about 68% on large operations, 13% on small. The tools exist; vendors packaged them for the large end only.' },
    { h: 'Europe farms small', p: 'Eurostat counts 62.8% of all EU farms at under five hectares. In Malta it is 97%. The overwhelming majority of European agriculture operates at the scale the precision-farming industry treats as an afterthought.' },
    { h: 'Consultancy does not scale down', p: 'An agronomist on retainer, soil labs, scouting programmes: the advisory layer that big estates buy is priced per visit and per hectare, which makes no sense at three hectares of vines or vegetables.' },
    { h: 'The data is already overhead', p: 'Sentinel satellites pass over every European field every few days, free of charge. Weather models cover every parish. The missing piece is a system that turns that data into one clear instruction a working farmer can act on.' },
  ],
  flowAlt: 'Abstract render of field rows converging into a single blue signal: the Field Intelligence data flow',
  cap: '97% OF MALTA’S FARMS ARE UNDER FIVE HECTARES',
  whoH: 'Built for the farms<br><span class="mute">statistics call small.</span>',
  first: {
    icon: 'leaf',
    h: 'The Mediterranean smallholding',
    p: 'VF designs Field Intelligence from Gozo outward: terraced plots, mixed crops, scarce water, no data team. If the system earns its keep on a Maltese smallholding, the EU’s smallest-farm landscape, it will earn it anywhere.',
    co: ['TERRACED PLOTS', 'MIXED CROPPING', 'WATER-SCARCE', 'NO DATA TEAM'],
  },
  aud: [
    { icon: 'users', h: 'Family farms', p: 'Operations run by one household, where every hour in front of a dashboard is an hour not spent in the field. The system answers questions; it does not create a new job.' },
    { icon: 'globe', h: 'Part-time growers', p: 'A huge share of European holdings are farmed alongside other work. Field Intelligence watches the fields on the days the farmer cannot.' },
    { icon: 'briefcase', h: 'Small cooperatives', p: 'Groups of growers who share machinery and markets can share field intelligence the same way: one system, many plots, each member seeing their own land.' },
    { icon: 'book', h: 'Agronomists and advisors', p: 'A multiplier for agronomy. Advisors serve more farms when the routine watching is already done and only the judgement calls remain.' },
  ],
  howH: 'From satellite pass<br><span class="mute">to one clear instruction.</span>',
  howLead: 'The measure of the system is whether a farmer standing in a field with wet boots and a phone gets an answer worth acting on.',
  outs: [
    { h: 'See stress before it spreads', p: 'Vegetation indices from every satellite pass, compared against the field’s own history, with anomalies flagged in plain language instead of colour maps the farmer has to decode.' },
    { h: 'Water on evidence', p: 'Irrigation guidance built from weather, soil class and observed canopy response, pointed at the Mediterranean reality of scarce, expensive water.' },
    { h: 'Know the season early', p: 'Yield outlooks that sharpen as the season runs, so you make selling, storage and labour decisions on the best available signal rather than last year’s memory.' },
  ],
  mechH: 'Free data in,<br><span class="mute">judgement out.</span>',
  mechLead: 'The architecture is humble by design: public satellite and weather data at the bottom, careful agronomic modelling in the middle, and a farmer-grade interface on top. No proprietary sensors required to start.',
  mechAlt: 'Layered render of satellite, weather and field data stacking into a single blue-lit plane',
  layers: [
    { h: 'The observation layer', p: 'Sentinel-2 imagery and regional weather models, ingested continuously per registered field boundary. This layer costs the farmer nothing: it is European public infrastructure, pointed at small fields at last.' },
    { h: 'The field model', p: 'Each plot gets its own running model: crop, planting date, soil class, irrigation setup, and its own multi-season history. The model judges anomalies against this field’s own record.' },
    { h: 'The advisory engine', p: 'Rules and models that convert observations into ranked, dated actions: scout this corner, hold irrigation two days, expect harvest pressure early. Every advisory carries its evidence.' },
    { h: 'The farmer surface', p: 'A phone-first interface in plain language, built for two-minute sessions. Optional sensor and machinery integrations extend it and are never the price of entry.' },
  ],
  roadH: 'The path from<br><span class="mute">first field to first harvest.</span>',
  road: [
    { h: 'Field zero', p: 'Live pilots on Maltese and Gozitan plots: field registration, satellite ingestion, first anomaly and irrigation advisories through a full growing season.' },
    { h: 'The advisory season', p: 'Multi-crop advisory coverage, seasonal yield outlooks, and the cooperative view: many plots, one system, per-member privacy.' },
    { h: 'The open field', p: 'Public availability across Mediterranean EU markets, sensor and machinery integrations, and advisor accounts for agronomists serving small-farm portfolios.' },
  ],
  paper: { h: 'Small fields, hard numbers', p: 'The VF position paper on the precision-agriculture adoption gap: why the technology skipped small farms, and the architecture choices that let it scale down.' },
  repo: { h: 'field-intelligence', p: 'Field-model and ingestion tooling. VF will publish the components that make sense to open (boundary handling, index computation) as the build matures.' },
  ctaH: 'Farming should not require<br><span class="mute">a data department.</span>',
  ctaLead: 'Field Intelligence is in build. If you farm small and want the same class of intelligence the big estates buy, register interest. Pilot fields shape the product.',
  faq: [
    { q: 'Which farms is Field Intelligence built for?', a: 'Small and family farms first. VF designs the system from Gozo outward: terraced plots, mixed crops, scarce water and no data team. It serves family farms, part-time growers, small cooperatives sharing one system across many plots, and agronomists advising small-farm portfolios. The precision-farming industry packaged its tools for estates measured in thousands of hectares; this scales the same class of analysis down.' },
    { q: 'Do I need sensors or new equipment?', a: 'No proprietary sensors are required to start. The observation layer uses Sentinel-2 satellite imagery and regional weather models, ingested per registered field boundary, which costs the farmer nothing because it is European public infrastructure. Optional sensor and machinery integrations extend the system later and are never the price of entry.' },
    { q: 'What does the system tell me?', a: 'Ranked, dated actions in plain language: scout this corner, hold irrigation two days, expect harvest pressure early. It flags crop stress from vegetation indices compared against the field’s own history, gives irrigation guidance built from weather, soil class and canopy response, and produces yield outlooks that sharpen as the season runs. Every advisory carries its evidence.' },
    { q: 'Does it work on a phone?', a: 'Yes. The farmer surface is a phone-first interface in plain language, built for two-minute sessions, so a farmer standing in a field with wet boots gets an answer worth acting on. The system answers questions; it does not create a new job in front of a dashboard. Web, iOS and Android are the target platforms.' },
    { q: 'When does Field Intelligence ship?', a: 'Field Intelligence is in build. The first phase runs live pilots on Maltese and Gozitan plots through a full growing season: field registration, satellite ingestion and the first anomaly and irrigation advisories. Multi-crop coverage, yield outlooks and the cooperative view follow, then public availability across Mediterranean EU markets. Register interest; pilot fields shape the product.' },
  ],
  related: ['grid-home-optimiser', 'the-apprentice', 'self-training-qc-vision'],
},

// ─── P·02 PRIVATE CARE WATCH ─────────────────────────────────────────
{
  slug: 'private-care-watch',
  name: 'Private Care Watch',
  pn: 'P·02',
  sector: 'ELDER CARE',
  titleTag: 'Elder monitoring, no cloud',
  metaDesc: 'Private Care Watch by VF Empire: in-home elder monitoring with fall alerts and routine-drift signals, processed on a hub the family owns. In build in Malta, EU.',
  ogTitle: 'Care that watches over, without watching.',
  ogDesc: 'Fall alerting and routine monitoring for ageing relatives, running on hardware in the home, never a cloud camera feed. On the VF build slate.',
  appCategory: 'LifestyleApplication',
  os: 'Home hub, iOS, Android',
  ldDesc: 'Private Care Watch is an elder-care monitoring system in development by VF Empire Corp Ltd: fall alerting, routine-drift and wellbeing monitoring processed on hardware inside the home, with family notifications and no cloud video.',
  img: 'p02',
  tagline: 'Care that watches over,<br><em class="i">without watching.</em>',
  sub: 'Families with ageing parents know the fear: the fall nobody heard, the quiet decline nobody measured. The market answer is cloud cameras in the living room. Private Care Watch is the other answer: monitoring and alerting on hardware the family owns, with nothing streamed anywhere.',
  chips: ['ON-PREMISE PROCESSING', 'NO CLOUD VIDEO', 'FAMILY ALERTS'],
  heroAlt: 'Minimal 3D render of an armchair with a small guardian orb beside it (Private Care Watch by VF Empire)',
  whyH: 'The fall is a fact of ageing.<br><span class="mute">The cloud camera is not.</span>',
  whyLead: 'Falls are one of the largest hidden emergencies in the world, and the wish to age at home is nearly universal. The technology offered to bridge those two facts mostly asks families to point internet-connected cameras at their parents. That trade should not be the default.',
  fails: [
    { h: 'The scale of the fall', p: 'The World Health Organization estimates around 684,000 people die from falls every year, with some 37 million falls severe enough to need medical attention. For older adults, the hours between falling and being found often decide the outcome.' },
    { h: 'Everyone wants to stay home', p: 'Surveys find about three-quarters of older adults want to age in their own homes. Families want that too; they lack a trustworthy way to know that today was a normal day.' },
    { h: 'Cloud cameras have already failed', p: 'The 2021 Verkada breach exposed live feeds from around 150,000 cameras, including inside care facilities. A camera feed that leaves the house is a camera feed that can leak. With grandparents, that risk class should be off the table.' },
    { h: 'Decline is quiet before it is loud', p: 'Before the emergency there is the drift: meals skipped, nights disturbed, movement slowing. Point sensors and panic buttons miss it; a system watching routine patterns can surface it while it is still a conversation.' },
  ],
  flowAlt: 'Abstract render of a home outline with a single blue pulse held inside its walls: data that never leaves',
  cap: 'WHO: ≈684,000 FALL DEATHS WORLDWIDE EVERY YEAR',
  whoH: 'For the family<br><span class="mute">an hour or a continent away.</span>',
  first: {
    icon: 'heart',
    h: 'The long-distance family',
    p: 'Millions of Europeans live a flight away from ageing parents; Malta knows this pattern well. VF designs Private Care Watch for that household: parents at home, children abroad, and a daily answer to the question that matters most, is everything normal today?',
    co: ['PARENTS AT HOME', 'CHILDREN ABROAD', 'DAILY REASSURANCE', 'ALERTS THAT MATTER'],
  },
  aud: [
    { icon: 'home', h: 'Ageing at home', p: 'The older adult who wants independence without isolation. The system is theirs, in their house, on their terms: presence-aware, with consent built into the architecture.' },
    { icon: 'users', h: 'Adult children', p: 'A calm daily signal instead of anxious phone checks. Alerts arrive when something needs attention; silence means all is well.' },
    { icon: 'heart', h: 'Live-in and visiting carers', p: 'Carers see the pattern between visits (what the nights looked like, whether routines held), so care hours go where the drift is.' },
    { icon: 'building', h: 'Small care residences', p: 'Family-scale homes that want resident safety without installing a surveillance estate. Same architecture, more rooms, same rule: processing stays on site.' },
  ],
  howH: 'Alerting when it matters.<br><span class="mute">Silence when it doesn’t.</span>',
  howLead: 'Private Care Watch is a monitoring and alerting system: it tells families what happened and what is drifting. It does not diagnose, and it does not promise prevention. That honesty is the product.',
  outs: [
    { h: 'Found in minutes', p: 'Fall and no-movement alerting designed to collapse the time between an incident and someone knowing, the single variable families can change.' },
    { h: 'The drift made visible', p: 'Routine baselines per household: sleep, movement, kitchen activity. The family sees the pattern bend early enough to act gently.' },
    { h: 'Privacy as architecture', p: 'All processing on the home hub. No video leaves the house; by design there is no cloud feed to breach, subpoena or resell.' },
  ],
  mechH: 'The hub is the product.<br><span class="mute">The cloud is not invited.</span>',
  mechLead: 'VF builds the system so the most sensitive data there is, footage of your parents in their own home, never becomes network traffic. Everything that watches, thinks locally.',
  mechAlt: 'Layered render of sensor signals resolving inside a single home unit with one blue status light',
  layers: [
    { h: 'The sensing layer', p: 'Radar, motion and door sensors first; optional cameras only where the household chooses them. Sensor selection favours modalities that never produce identifiable imagery at all.' },
    { h: 'The home hub', p: 'A local unit running all detection models on-premise. Fall inference, presence tracking and routine modelling happen here; the device processes raw sensor data and discards it.' },
    { h: 'The pattern engine', p: 'Longitudinal baselines built per person, per home. Alerts are judged against this household’s normal, which keeps false alarms low and real drift visible.' },
    { h: 'The family surface', p: 'Phone apps carrying alerts and daily summaries: status and events, never a live feed. Each family member sees only what the older adult consented to share.' },
  ],
  roadH: 'From one living room<br><span class="mute">to any family that needs it.</span>',
  road: [
    { h: 'The first household', p: 'Hub hardware selection, fall and presence detection running local, family alerting proven end-to-end in real homes.' },
    { h: 'The pattern season', p: 'Routine-drift modelling over months of baseline data, carer views, and the consent framework hardened with real families using it.' },
    { h: 'The care circle', p: 'General availability, multi-room and small-residence configurations, and integrations with local emergency contacts and care providers.' },
  ],
  paper: { h: 'The no-cloud care thesis', p: 'The VF position paper on elder monitoring: why in-home processing is the only defensible architecture for this data class, and what alerting can and cannot promise.' },
  repo: { h: 'private-care-watch', p: 'Hub firmware and detection pipeline. VF will build privacy-critical components for auditability, so families can verify nothing leaves the house.' },
  ctaH: 'Their dignity.<br><span class="mute">Your peace of mind. No trade.</span>',
  ctaLead: 'Private Care Watch is in build. If your family is living the long-distance question, register interest; pilot households shape what this becomes.',
  faq: [
    { q: 'Where does my parents’ data go?', a: 'It stays in the house. All detection runs on a home hub the family owns: fall inference, presence tracking and routine modelling happen there, and the device processes raw sensor data and discards it. No video leaves the home, so by design there is no cloud feed to breach, subpoena or resell. Family apps receive status and events only.' },
    { q: 'Does it use cameras?', a: 'Radar, motion and door sensors come first. Optional cameras are used only where the household chooses them, and sensor selection favours modalities that never produce identifiable imagery at all. Whatever the sensing mix, processing stays on the hub in the home, and the family surface carries alerts and daily summaries, never a live feed.' },
    { q: 'What does Private Care Watch alert me to?', a: 'Falls and no-movement events, with alerting designed to collapse the time between an incident and someone knowing. It also builds routine baselines per household (sleep, movement, kitchen activity) so the family sees the pattern bend early enough to act gently. Alerts are judged against this household’s normal, which keeps false alarms low. Silence means all is well.' },
    { q: 'Does it diagnose or prevent falls?', a: 'No. Private Care Watch is a monitoring and alerting system: it tells families what happened and what is drifting. It does not diagnose and it does not promise prevention. That honesty is the product. The older adult consents to what is shared, and each family member sees only what that consent allows.' },
    { q: 'Who is it for?', a: 'The long-distance family: parents at home, children abroad, and a daily answer to whether everything is normal today. It also serves live-in and visiting carers, who see the pattern between visits, and small care residences that want resident safety without a surveillance estate, on the same rule that processing stays on site.' },
    { q: 'When will it be available?', a: 'Private Care Watch is in build. The first phase covers hub hardware selection, local fall and presence detection and family alerting proven end-to-end in real homes. Routine-drift modelling, carer views and the consent framework follow, then general availability with multi-room and small-residence configurations. Register interest; pilot households shape what this becomes.' },
  ],
  related: ['triage-continuity', 'vf-home', 'grid-home-optimiser'],
},

// ─── P·03 THE APPRENTICE ─────────────────────────────────────────────
{
  slug: 'the-apprentice',
  name: 'The Apprentice',
  pn: 'P·03',
  sector: 'SKILLED TRADES',
  titleTag: 'Diagnostic copilot for trades',
  metaDesc: 'The Apprentice by VF Empire: a diagnostic and code-reference copilot for electricians, plumbers and mechanics, built for the job site. In build in Malta, EU.',
  ogTitle: 'The AI copilot the trades were never given',
  ogDesc: 'Diagnostics, code reference and job documentation for electricians, plumbers and mechanics, built for hands that are usually full. On the VF build slate.',
  appCategory: 'BusinessApplication',
  os: 'iOS, Android, Web',
  ldDesc: 'The Apprentice is a skilled-trades assistant in development by VF Empire Corp Ltd: diagnostic reasoning, regulation and code reference, and job documentation for electricians, plumbers, HVAC technicians and mechanics. It informs the professional; sign-off always remains with the qualified tradesperson.',
  img: 'p03',
  tagline: 'Every master deserves<br><em class="i">an apprentice.</em>',
  sub: 'The office got copilots for email, code and slides. The people who keep buildings powered, warm and dry got nothing. The Apprentice is a working copilot for the trades: diagnostics, code reference and paperwork, built for the job site.',
  chips: ['HANDS-FREE FIRST', 'CODE-AWARE', 'TRADESPERSON SIGNS OFF'],
  heroAlt: 'Minimal 3D render of an open toolbox with one blue wrench (The Apprentice by VF Empire)',
  whyH: 'The trades are short-handed.<br><span class="mute">And the tools went to the office.</span>',
  whyLead: 'The skilled-trades shortage is one of Europe’s most measured problems, and the knowledge burden on each remaining tradesperson keeps growing. AI landed everywhere except the van.',
  fails: [
    { h: 'The shortage is structural', p: 'Germany’s ifo institute found 22.7% of firms reporting skilled-labour shortages constraining business, with construction and trades among the hardest hit. Fewer hands must now carry more knowledge, faster.' },
    { h: 'The codebook never stops moving', p: 'Electrical codes turn over on multi-year cycles: the US NEC alone every three years, and each EU state maintains its own evolving norms. A career spans decades of moving regulation, and looking it up mid-job is unpaid time.' },
    { h: 'Vehicles became computers', p: 'Industry surveys report around half of automotive technicians feel underprepared for the electronics now arriving in vehicles. The diagnostic layer of a modern car outgrew the training most mechanics were given.' },
    { h: 'The paperwork eats the evening', p: 'Quotes, job reports, compliance records, photos filed to the right customer: the tradesperson does the administrative tail at the kitchen table, after the billable day ends.' },
  ],
  flowAlt: 'Abstract render of tool silhouettes aligning along one blue guide line: knowledge flowing to the job',
  cap: 'THE ELECTRICAL CODE CHANGES EVERY THREE YEARS. A CAREER LASTS FORTY.',
  whoH: 'For the people<br><span class="mute">who fix the real world.</span>',
  first: {
    icon: 'wrench',
    h: 'The independent tradesperson',
    p: 'One van, one set of hands, and every role at once (technician, estimator, clerk and archive). VF builds The Apprentice for this operator first: the sole trader who has no back office and no time to become one.',
    co: ['ONE-PERSON FIRM', 'ON-SITE ALL DAY', 'EVERY TRADE HAT', 'NO BACK OFFICE'],
  },
  aud: [
    { icon: 'bolt', h: 'Electricians', p: 'Fault-finding support and norm reference at the panel, asked by voice, answered with sources. The system informs the diagnosis; the qualified electrician makes and signs it.' },
    { icon: 'home', h: 'Plumbers & HVAC', p: 'System diagnostics, spec lookups and installation references for heat pumps, boilers and the fast-changing efficiency rules around them.' },
    { icon: 'truck', h: 'Mechanics', p: 'A diagnostic reasoning partner for vehicles that are now rolling computers: symptom to hypothesis to test sequence, with the technician in charge.' },
    { icon: 'users', h: 'Small trade firms', p: 'Crews of two to ten who want every member carrying the firm’s collective know-how, and job documentation drafted on site.' },
  ],
  howH: 'Knowledge at the panel,<br><span class="mute">where the work is.</span>',
  howLead: 'The Apprentice is an assistant. It brings the reference material, the reasoning support and the paperwork; the judgement and the sign-off belong to the professional, legally and by design.',
  outs: [
    { h: 'Diagnose with a second brain', p: 'Symptom-driven reasoning that proposes causes and test sequences, learning the shape of each trade’s real failure patterns. The tradesperson stays the decision-maker.' },
    { h: 'The code, cited', p: 'Regulation and norm reference with sources shown: a fast, checkable answer instead of a memory gamble or an evening of PDF archaeology.' },
    { h: 'Paperwork done on site', p: 'Job reports, quotes and compliance documentation drafted from photos and dictation before the van door closes, the kitchen-table shift deleted.' },
  ],
  mechH: 'Built for gloves,<br><span class="mute">noise and no signal.</span>',
  mechLead: 'A job site is the hostile opposite of a desk: loud, dirty, offline in basements and plant rooms. VF engineers the system from those constraints.',
  mechAlt: 'Layered render of a rugged device stack with one blue diagnostic beam',
  layers: [
    { h: 'The site interface', p: 'Voice-first and glance-based interaction on the phone the tradesperson already carries. Hands stay on the work; the copilot listens and answers.' },
    { h: 'The knowledge core', p: 'Curated trade knowledge, norms and manufacturer documentation, retrieval-grounded so answers carry citations. Per-country code editions handled explicitly, never blended.' },
    { h: 'The diagnostic engine', p: 'Structured reasoning over symptoms, measurements and history: hypothesis, discriminating test, next step. The engine states its confidence and admits uncertainty.' },
    { h: 'The paperwork mill', p: 'Photos, dictated notes and job data compiled into quotes, reports and compliance records in the firm’s own format, reviewed and signed by the human, always.' },
  ],
  roadH: 'One trade deep,<br><span class="mute">then the whole van fleet.</span>',
  road: [
    { h: 'The electrical spine', p: 'First trade vertical: electrician diagnostics and norm reference for pilot markets, voice-first site interface, documentation drafting proven with working sparks.' },
    { h: 'Three trades wide', p: 'Plumbing, HVAC and automotive verticals; firm accounts with shared job history; per-country code packs expanding across the EU.' },
    { h: 'The trade standard', p: 'General availability, manufacturer-documentation partnerships, and apprentice-training modes that turn every job into teaching material for the next generation.' },
  ],
  paper: { h: 'Copilots for the real economy', p: 'The VF position paper on trade-work AI: why the assistant model fits the trades, and where the sign-off line must legally and ethically stay.' },
  repo: { h: 'the-apprentice', p: 'Retrieval core and documentation pipeline. VF will open code-reference tooling with public sources where licensing of the underlying norms allows.' },
  ctaH: 'The trades kept<br><span class="mute">the lights on. Return the favour.</span>',
  ctaLead: 'The Apprentice is in build, electricians first. If you work a trade and want a copilot that respects the craft, register interest; pilot tradespeople steer the build.',
  faq: [
    { q: 'Which trades does The Apprentice cover?', a: 'Electricians first, then plumbing, HVAC and automotive. The first vertical is electrician diagnostics and norm reference for pilot markets. Plumbers and HVAC technicians get system diagnostics and installation references for heat pumps and boilers; mechanics get a diagnostic reasoning partner for vehicles that are now rolling computers. Small trade firms of two to ten share the firm’s collective know-how.' },
    { q: 'Does it work with gloves on and no signal?', a: 'It is engineered for the job site: loud, dirty, offline in basements and plant rooms. Interaction is voice-first and glance-based on the phone the tradesperson already carries, so hands stay on the work while the copilot listens and answers. The build treats no signal as a design constraint from the start.' },
    { q: 'Who signs off the work?', a: 'The qualified tradesperson, always. The Apprentice is an assistant: it brings reference material, reasoning support and paperwork, and the judgement and the sign-off stay with the professional, legally and by design. The diagnostic engine states its confidence and admits uncertainty; the human makes and signs the diagnosis.' },
    { q: 'Are code references cited?', a: 'Yes. The knowledge core holds curated trade knowledge, norms and manufacturer documentation, retrieval-grounded so every answer carries a citation. Per-country code editions are handled explicitly and never blended, which matters when each EU state maintains its own evolving norms. You get a fast, checkable answer instead of an evening of PDF archaeology.' },
    { q: 'Can it do the paperwork?', a: 'Job reports, quotes and compliance records are drafted from photos and dictated notes before the van door closes, in the firm’s own format. The human reviews and signs every document. The target is the kitchen-table administrative shift after the billable day: the paperwork gets done on site instead.' },
    { q: 'When does it ship?', a: 'The Apprentice is in build, electricians first. The electrical spine comes first: diagnostics, norm reference, the voice-first site interface and documentation drafting proven with working sparks. Plumbing, HVAC and automotive verticals follow with firm accounts and per-country code packs across the EU. Register interest; pilot tradespeople steer the build.' },
  ],
  related: ['site-truth-engine', 'self-training-qc-vision', 'nav-it'],
},

// ─── P·04 BACK-OFFICE AUTOPILOT ──────────────────────────────────────
{
  slug: 'back-office-autopilot',
  name: 'Back-Office Autopilot',
  pn: 'P·04',
  sector: 'SMALL BUSINESS',
  titleTag: 'Micro-firm back office',
  metaDesc: 'Back-Office Autopilot by VF Empire: invoicing, payment chasing, scheduling and filing preparation for firms under ten people. In build in Malta, EU.',
  ogTitle: 'Nine in ten EU firms have no back office. Now they do.',
  ogDesc: 'Invoicing, chasing, scheduling and filing preparation for micro-firms: the administrative engine small business never had. On the VF build slate.',
  appCategory: 'BusinessApplication',
  os: 'Web, iOS, Android',
  ldDesc: 'Back-Office Autopilot is a small-business administration system in development by VF Empire Corp Ltd: invoicing, payment follow-up, scheduling and preparation of filings for owner approval, designed for firms with fewer than ten people.',
  img: 'p04',
  tagline: 'The department<br><em class="i">you never had to hire.</em>',
  sub: 'More than nine in ten EU businesses have fewer than ten people, and no back office. The owner is the back office, at night. Back-Office Autopilot runs the administrative engine: invoices out, payments chased, schedule kept, filings prepared for your approval.',
  chips: ['MICRO-FIRM FIRST', 'CHASES POLITELY', 'YOU APPROVE EVERYTHING'],
  heroAlt: 'Minimal 3D render of stacked paper trays with one floating blue sheet: Back-Office Autopilot by VF Empire',
  whyH: 'Small firms do the work.<br><span class="mute">Then the work after the work.</span>',
  whyLead: 'The administrative burden on micro-businesses is a measurable drag on Europe’s largest employer class, paid in unpaid evenings and late cashflow.',
  fails: [
    { h: 'Getting paid is a second job', p: 'European payment reports consistently find around half of suppliers paid later than agreed, and Intrum has estimated the cost of chasing payments to European businesses in the hundreds of billions of euros a year. For a micro-firm, one late invoice is a cashflow event.' },
    { h: 'Enterprise tools don’t scale down', p: 'ERP suites assume a finance team, an implementation budget and months of onboarding. A three-person firm needs the outcome (money in, obligations met) without adopting an enterprise’s process weight.' },
    { h: 'The owner is the bottleneck', p: 'Quoting, invoicing, scheduling, reminders, receipts, filings: in a sub-ten-person firm every one of these runs through the same person who also does the actual work and the selling.' },
    { h: 'Deadlines don’t care', p: 'VAT periods, payroll dates, statutory returns: the calendar of obligations runs whether the firm is busy or not, and every missed date has a fine attached. Memory is not a compliance system.' },
  ],
  flowAlt: 'Abstract render of scattered documents converging into one ordered blue channel: the administrative flow tamed',
  cap: 'MORE THAN 9 IN 10 EU BUSINESSES HAVE FEWER THAN 10 PEOPLE, AND NO BACK OFFICE',
  whoH: 'For the firm where<br><span class="mute">the owner is every department.</span>',
  first: {
    icon: 'briefcase',
    h: 'Our own companies, first',
    p: 'VF Empire runs the exact problem this system solves: a group of small companies across two EU countries with invoices, filings and obligations and no administrative staff. Back-Office Autopilot is dogfooded on our own group before it is offered to anyone else.',
    co: ['MULTI-COMPANY', 'TWO EU JURISDICTIONS', 'ZERO ADMIN STAFF', 'PROVEN ON OURSELVES'],
  },
  aud: [
    { icon: 'wrench', h: 'Trades & service firms', p: 'Job done, invoice out the same evening, follow-up handled with polite persistence. The cash cycle tightens without the owner sending a single awkward reminder.' },
    { icon: 'users', h: 'Micro-agencies & freelancers', p: 'Proposals, recurring invoices, time-based billing and the client-chasing dance, automated up to the point of the owner’s one-tap approval.' },
    { icon: 'building', h: 'Shops & hospitality', p: 'Supplier invoices, staff scheduling and the drumbeat of periodic filings, handled in the background of a business that lives on foot traffic.' },
    { icon: 'doc', h: 'The accountant relationship', p: 'The system prepares (books ordered, documents filed, returns drafted) so the accountant’s hours go on judgement, not sorting. Professional advisors stay exactly where the law puts them.' },
  ],
  howH: 'The engine runs.<br><span class="mute">You approve. That’s the whole job.</span>',
  howLead: 'The design principle is approval, not autonomy: the system drafts, chases, schedules and prepares, and the owner remains the signature on everything that leaves the building.',
  outs: [
    { h: 'Invoices that follow up', p: 'From quote to invoice to reminder sequence, automatically: firm but courteous, escalating on a schedule the owner sets once.' },
    { h: 'Filings prepared, not missed', p: 'The obligation calendar tracked per company and jurisdiction, documents assembled ahead of every date, returns prepared for the owner’s approval, or their advisor’s.' },
    { h: 'Evenings returned', p: 'The kitchen-table administrative shift is the target metric. The system succeeds when the paperwork hour after dinner stops existing.' },
  ],
  mechH: 'One firm, one graph,<br><span class="mute">every obligation on it.</span>',
  mechLead: 'Underneath, the system maintains a single living model of the firm (customers, jobs, money and deadlines) and drives every workflow from it.',
  mechAlt: 'Layered render of an ordered document lattice with one blue approval seal',
  layers: [
    { h: 'The firm graph', p: 'Customers, suppliers, jobs, invoices, obligations and their deadlines in one connected model per company, multi-company from day one, because small owners often run more than one entity.' },
    { h: 'The workflow engine', p: 'Invoicing runs, reminder sequences, scheduling and document collection executed as long-running processes that survive the owner’s busiest weeks.' },
    { h: 'The filing preparer', p: 'Jurisdiction-aware assembly of returns and statutory documents, prepared for approval by the owner or their professional advisor. The system prepares; it does not purport to advise.' },
    { h: 'The approval surface', p: 'A phone-first review queue: everything outbound (invoice, reminder, filing) passes the owner’s thumb before it moves. Control without the labour.' },
  ],
  roadH: 'Proven on our own books<br><span class="mute">before it touches yours.</span>',
  road: [
    { h: 'The house pilot', p: 'The full loop (invoicing, chasing, obligation calendar, filing preparation) running live on the VF group’s own companies across Malta and Germany.' },
    { h: 'The first hundred firms', p: 'External pilot cohort: trades, agencies and shops, with accountant-collaboration workflows and expanded jurisdiction packs.' },
    { h: 'The open desk', p: 'General availability across EU micro-business markets, banking integrations for payment matching, and the payroll and HR modules that complete the department.' },
  ],
  paper: { h: 'The missing department', p: 'The VF position paper on micro-firm administration: the true cost of the owner-run back office, and why approval-based automation is the honest architecture.' },
  repo: { h: 'back-office-autopilot', p: 'Workflow engine and firm-graph core. Jurisdiction-pack schemas will be published so the obligation calendar can be community-audited.' },
  ctaH: 'You started the firm<br><span class="mute">to do the work. Do the work.</span>',
  ctaLead: 'Back-Office Autopilot is in build, running on our own companies first. If your evenings belong to paperwork, register interest; the pilot cohort is drawn from this list.',
  faq: [
    { q: 'Which firms is Back-Office Autopilot for?', a: 'Firms with fewer than ten people and no back office: trades and service firms, micro-agencies and freelancers, shops and hospitality. It is multi-company from day one, because small owners often run more than one entity. VF runs it on its own group of small companies across Malta and Germany before offering it to anyone else.' },
    { q: 'What does it do?', a: 'Invoices out, payments chased, schedule kept, filings prepared. It runs quote-to-invoice-to-reminder sequences that escalate on a schedule the owner sets once, tracks the obligation calendar per company and jurisdiction, and assembles documents ahead of every date. The target metric is the paperwork hour after dinner ceasing to exist.' },
    { q: 'Does it send anything without me?', a: 'No. The design principle is approval: the system drafts, chases, schedules and prepares, and the owner remains the signature on everything that leaves the building. A phone-first review queue holds every outbound invoice, reminder and filing until the owner’s thumb passes it. Control without the labour.' },
    { q: 'Does it replace my accountant?', a: 'No. The system prepares: books ordered, documents filed, returns drafted for approval by the owner or their professional advisor. It does not purport to advise. Professional advisors stay exactly where the law puts them, and their hours go on judgement instead of sorting.' },
    { q: 'What is the status?', a: 'Back-Office Autopilot is in build, running on VF’s own companies first. The house pilot runs the full loop (invoicing, chasing, obligation calendar, filing preparation) live across Malta and Germany. An external pilot cohort of trades, agencies and shops follows, drawn from the interest list, then general availability across EU micro-business markets.' },
  ],
  related: ['the-apprentice', 'fileit', 'vf-mail'],
},

// ─── P·05 EVERYDAY-LAW NAVIGATOR ─────────────────────────────────────
{
  slug: 'everyday-law-navigator',
  name: 'Everyday-Law Navigator',
  pn: 'P·05',
  sector: 'LEGAL ACCESS',
  titleTag: 'Plain-language law guide',
  metaDesc: 'Everyday-Law Navigator by VF Empire: plain-language legal information on tenancy, consumer and employment rights, every source cited. In build in Malta, EU.',
  ogTitle: 'the law applies to everyone. Understanding it shouldn’t cost £300 an hour.',
  ogDesc: 'Plain-language legal information for tenancy, consumer, employment and everyday disputes: organised, sourced, honest about its limits. On the VF build slate.',
  appCategory: 'ReferenceApplication',
  os: 'Web, iOS, Android',
  ldDesc: 'Everyday-Law Navigator is a legal-information system in development by VF Empire Corp Ltd: plain-language guidance on rights, contracts, tenancy and everyday disputes with sources shown. It provides legal information, not legal advice, and routes users to qualified professionals and existing advice services where matters require them.',
  img: 'p05',
  tagline: 'Know where you stand,<br><em class="i">before you decide where to go.</em>',
  sub: 'Most legal problems never reach a lawyer. They reach a search bar, a forum, or nothing at all. Everyday-Law Navigator organises the law that governs ordinary life into plain language with sources shown. It gives legal information, not legal advice, and is honest about that line.',
  chips: ['PLAIN LANGUAGE', 'SOURCES SHOWN', 'NOT LEGAL ADVICE'],
  heroAlt: 'Minimal 3D render of balance scales holding one blue cube: Everyday-Law Navigator by VF Empire',
  whyH: 'Justice has a gap.<br><span class="mute">Billions of people live in it.</span>',
  whyLead: 'The unmet need for legal understanding is one of the largest measured gaps in the world, and the help that exists is scattered across agencies, jurisdictions and hourly rates most people will never pay.',
  fails: [
    { h: 'The gap is planetary', p: 'The World Justice Project estimates 5.1 billion people worldwide have unmet justice needs, including 1.4 billion with unresolved civil disputes. Most of those problems are everyday-sized: a deposit, a contract, a dismissal, a faulty product.' },
    { h: 'The meter runs in hundreds', p: 'Hourly rates commonly run £140–570 in the UK and €150–400 in Germany. For a €900 dispute, professional help is economically irrational, so people go without understanding, or go alone.' },
    { h: 'Alone before the court', p: 'Small-claims and tribunal systems are built for self-representation, yet the people using them get little help understanding procedure, evidence or their own position before walking in.' },
    { h: 'Good help is fragmented', p: 'Citizens Advice, Verbraucherzentralen, legal-aid schemes, ombudsmen: real help exists, and this system routes to it. The failure is fragmentation. Knowing which door, in which jurisdiction, with which deadline, is itself a legal-research task.' },
  ],
  flowAlt: 'Abstract render of tangled paths resolving into one clear blue route: the way through the system',
  cap: 'AN ESTIMATED 5.1 BILLION PEOPLE WORLDWIDE HAVE UNMET JUSTICE NEEDS',
  whoH: 'For everyone the<br><span class="mute">hourly rate priced out.</span>',
  first: {
    icon: 'shield',
    h: 'The tenant with a deposit problem',
    p: 'The archetype user: a real dispute, a few hundred euros at stake, a landlord who stopped answering, and no idea whether the law is on their side. The Navigator’s first job is that person: position explained, options mapped, deadlines flagged, right door pointed to.',
    co: ['REAL STAKES', 'SMALL AMOUNTS', 'NO LAWYER BUDGET', 'NEEDS A MAP'],
  },
  aud: [
    { icon: 'home', h: 'Tenants & landlords', p: 'Deposits, repairs, notice periods, rent rules: the highest-volume legal territory in ordinary life, explained per jurisdiction with the statute shown.' },
    { icon: 'briefcase', h: 'Employees', p: 'Contracts, dismissal, unpaid wages, working time: the law, the deadlines, and the point at which a matter needs a lawyer or a union.' },
    { icon: 'users', h: 'Consumers', p: 'Faulty goods, cancelled flights, subscription traps, warranty rights: EU consumer law is strong and largely unused, because few people can find their piece of it.' },
    { icon: 'doc', h: 'Micro-businesses', p: 'The sole trader reading a contract at midnight gets obligations, red flags and standard terms explained before signing, with professional review flagged where it matters.' },
  ],
  howH: 'Understanding first.<br><span class="mute">The right door second.</span>',
  howLead: 'The Navigator does not replace lawyers and never claims to. It moves you from confused to informed, and routes you to qualified help and existing advice services the moment a matter crosses the line.',
  outs: [
    { h: 'Your position, in plain words', p: 'The relevant law for your situation and jurisdiction, explained in ordinary language with every source cited and checkable.' },
    { h: 'Options and deadlines mapped', p: 'The paths available (complaint, ombudsman, small claims, walking away) with costs, time limits and realistic effort laid out side by side.' },
    { h: 'Routed to the right door', p: 'The moment a matter needs a professional, the system says so plainly and points to the right one: legal aid, advice agencies, ombudsmen or a qualified lawyer.' },
  ],
  mechH: 'Sourced law in.<br><span class="mute">Honest boundaries out.</span>',
  mechLead: 'VF built the architecture around the one failure this category cannot afford: confident wrongness. The grounding engine ties every answer to cited law and resolves the jurisdiction first; a boundary layer fences what the system must not do.',
  mechAlt: 'Layered render of statute volumes feeding one clear blue answer plane',
  layers: [
    { h: 'The law corpus', p: 'Statutes, regulations and official guidance ingested per jurisdiction with version and validity tracking, because law changes and the corpus must know when it did.' },
    { h: 'The grounding engine', p: 'Retrieval-first answering: every statement traceable to a cited source, jurisdiction resolved before anything else, and no answer where the corpus has no ground.' },
    { h: 'The boundary layer', p: 'Hard rules encoding the information/advice line per jurisdiction. The layer detects matters requiring reserved legal activities and routes them out by architecture.' },
    { h: 'The navigator surface', p: 'Situation-first interface: describe the problem, get position, options, deadlines and documents, with the routing directory of real-world help one tap away.' },
  ],
  roadH: 'One jurisdiction proven,<br><span class="mute">then the map grows.</span>',
  road: [
    { h: 'The first corpus', p: 'Tenancy and consumer law for the pilot jurisdictions, grounding and boundary layers proven, routing directory of advice services live.' },
    { h: 'The everyday span', p: 'Employment and contract coverage, document explanation, and small-claims procedural guides per jurisdiction.' },
    { h: 'The public map', p: 'General availability across initial EU markets and the UK, multilingual delivery, and partnerships with the advice organisations already doing this work.' },
  ],
  paper: { h: 'The line we will not cross', p: 'The VF position paper on legal-information AI: the honest boundary between information and advice, why it exists, and how to build a system that keeps it.' },
  repo: { h: 'everyday-law-navigator', p: 'Corpus tooling and grounding pipeline. VF will publish the boundary-layer rule sets; the safety architecture of a system like this should be inspectable.' },
  ctaH: 'The law already<br><span class="mute">protects you. Now find out how.</span>',
  ctaLead: 'Everyday-Law Navigator is in build. If you’ve ever faced a dispute with no idea where you stood, register interest. Real cases shape the corpus priorities.',
  faq: [
    { q: 'Is Everyday-Law Navigator legal advice?', a: 'No. It provides legal information: your position in plain words, with every source cited and checkable. A boundary layer encodes the information/advice line per jurisdiction and routes matters requiring reserved legal activities to legal aid, advice agencies, ombudsmen or a qualified lawyer. The Navigator moves you from confused to informed, and says plainly when a professional is needed.' },
    { q: 'Which areas of law does it cover?', a: 'Tenancy and consumer law come first: deposits, repairs, notice periods, rent rules, faulty goods, cancelled flights, subscription traps and warranty rights. Employment and contract coverage follows, with document explanation and small-claims procedural guides per jurisdiction. Micro-businesses get contract obligations and red flags explained before signing.' },
    { q: 'Which countries does it cover?', a: 'The pilot jurisdictions first, with the corpus ingested per jurisdiction and version tracking because law changes. The grounding engine resolves your jurisdiction before anything else. The public map phase targets general availability across initial EU markets and the UK, with multilingual delivery and partnerships with the advice organisations already doing this work.' },
    { q: 'How do I know an answer is right?', a: 'Every statement traces to a cited source. The grounding engine is retrieval-first: statutes, regulations and official guidance are ingested with validity tracking, and the system gives no answer where the corpus has no ground. VF built the architecture around the one failure this category cannot afford, confident wrongness.' },
    { q: 'When does it ship?', a: 'Everyday-Law Navigator is in build. The first corpus covers tenancy and consumer law for the pilot jurisdictions, with grounding and boundary layers proven and a routing directory of advice services live. Employment and contract coverage follows. Register interest; real cases shape the corpus priorities.' },
  ],
  related: ['citizen-services-desk', 'claims-advocate'],
},

];
